// Сервис управления API-ключами.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/api_key_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/api_key_admin.proto.
 */
export const file_emh_v1_api_key_admin: GenFile = /*@__PURE__*/
  fileDesc("ChplbWgvdjEvYXBpX2tleV9hZG1pbi5wcm90bxIGZW1oLnYxIqsCCgZBcGlLZXkSCgoCaWQYASABKAkSDgoGa2V5X2lkGAIgASgJEgwKBG5hbWUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSDAoEcm9sZRgFIAEoCRISCgpjcmVhdGVkX2J5GAYgASgJEi4KCnJldm9rZWRfYXQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmV4cGlyZXNfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDGxhc3RfdXNlZF9hdBgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKY3JlYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAifwoTQ3JlYXRlQXBpS2V5UmVxdWVzdBIVCgRuYW1lGAEgASgJQge6SARyAhABEhMKC2Rlc2NyaXB0aW9uGAIgASgJEgwKBHJvbGUYAyABKAkSLgoKZXhwaXJlc19hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiSQoUQ3JlYXRlQXBpS2V5UmVzcG9uc2USHwoHYXBpX2tleRgBIAEoCzIOLmVtaC52MS5BcGlLZXkSEAoIZnVsbF9rZXkYAiABKAkiLQoSTGlzdEFwaUtleXNSZXF1ZXN0EhcKD2luY2x1ZGVfcmV2b2tlZBgBIAEoCCI3ChNMaXN0QXBpS2V5c1Jlc3BvbnNlEiAKCGFwaV9rZXlzGAEgAygLMg4uZW1oLnYxLkFwaUtleSIrChNSZXZva2VBcGlLZXlSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABASInChRSZXZva2VBcGlLZXlSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIMvIBChJBcGlLZXlBZG1pblNlcnZpY2USSQoMQ3JlYXRlQXBpS2V5EhsuZW1oLnYxLkNyZWF0ZUFwaUtleVJlcXVlc3QaHC5lbWgudjEuQ3JlYXRlQXBpS2V5UmVzcG9uc2USRgoLTGlzdEFwaUtleXMSGi5lbWgudjEuTGlzdEFwaUtleXNSZXF1ZXN0GhsuZW1oLnYxLkxpc3RBcGlLZXlzUmVzcG9uc2USSQoMUmV2b2tlQXBpS2V5EhsuZW1oLnYxLlJldm9rZUFwaUtleVJlcXVlc3QaHC5lbWgudjEuUmV2b2tlQXBpS2V5UmVzcG9uc2VCPVo7Y29kZWJlcmcub3JnL1RocjBUVDFlL2VtaC9iYWNrZW5kL2ludGVybmFsL2dlbi9lbWgvdjE7ZW1odjFiBnByb3RvMw", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * ApiKey метаданные API-ключа (без секретной части).
 *
 * @generated from message emh.v1.ApiKey
 */
export type ApiKey = Message<"emh.v1.ApiKey"> & {
  /**
   * id - UUID записи ключа.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * key_id - публичный идентификатор ключа (не секрет).
   *
   * @generated from field: string key_id = 2;
   */
  keyId: string;

  /**
   * name - человекочитаемое имя ключа.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * description - описание назначения ключа.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * role - права ключа.
   *
   * @generated from field: string role = 5;
   */
  role: string;

  /**
   * created_by - кто создал ключ.
   *
   * @generated from field: string created_by = 6;
   */
  createdBy: string;

  /**
   * revoked_at - время отзыва (пусто если активен).
   *
   * @generated from field: google.protobuf.Timestamp revoked_at = 7;
   */
  revokedAt?: Timestamp | undefined;

  /**
   * expires_at - срок действия (пусто если бессрочный).
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 8;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * last_used_at - время последнего использования.
   *
   * @generated from field: google.protobuf.Timestamp last_used_at = 9;
   */
  lastUsedAt?: Timestamp | undefined;

  /**
   * created_at - время создания.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * ApiKey метаданные API-ключа (без секретной части).
 *
 * @generated from message emh.v1.ApiKey
 */
export type ApiKeyJson = {
  /**
   * id - UUID записи ключа.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * key_id - публичный идентификатор ключа (не секрет).
   *
   * @generated from field: string key_id = 2;
   */
  keyId?: string;

  /**
   * name - человекочитаемое имя ключа.
   *
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * description - описание назначения ключа.
   *
   * @generated from field: string description = 4;
   */
  description?: string;

  /**
   * role - права ключа.
   *
   * @generated from field: string role = 5;
   */
  role?: string;

  /**
   * created_by - кто создал ключ.
   *
   * @generated from field: string created_by = 6;
   */
  createdBy?: string;

  /**
   * revoked_at - время отзыва (пусто если активен).
   *
   * @generated from field: google.protobuf.Timestamp revoked_at = 7;
   */
  revokedAt?: TimestampJson;

  /**
   * expires_at - срок действия (пусто если бессрочный).
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 8;
   */
  expiresAt?: TimestampJson;

  /**
   * last_used_at - время последнего использования.
   *
   * @generated from field: google.protobuf.Timestamp last_used_at = 9;
   */
  lastUsedAt?: TimestampJson;

  /**
   * created_at - время создания.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: TimestampJson;
};

/**
 * Describes the message emh.v1.ApiKey.
 * Use `create(ApiKeySchema)` to create a new message.
 */
export const ApiKeySchema: GenMessage<ApiKey, {jsonType: ApiKeyJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 0);

/**
 * CreateApiKeyRequest запрос на создание API-ключа.
 *
 * @generated from message emh.v1.CreateApiKeyRequest
 */
export type CreateApiKeyRequest = Message<"emh.v1.CreateApiKeyRequest"> & {
  /**
   * name - имя ключа (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * description - описание назначения.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * role - права ключа (по умолчанию admin).
   *
   * @generated from field: string role = 3;
   */
  role: string;

  /**
   * expires_at - срок действия (опционально).
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * CreateApiKeyRequest запрос на создание API-ключа.
 *
 * @generated from message emh.v1.CreateApiKeyRequest
 */
export type CreateApiKeyRequestJson = {
  /**
   * name - имя ключа (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * description - описание назначения.
   *
   * @generated from field: string description = 2;
   */
  description?: string;

  /**
   * role - права ключа (по умолчанию admin).
   *
   * @generated from field: string role = 3;
   */
  role?: string;

  /**
   * expires_at - срок действия (опционально).
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: TimestampJson;
};

/**
 * Describes the message emh.v1.CreateApiKeyRequest.
 * Use `create(CreateApiKeyRequestSchema)` to create a new message.
 */
export const CreateApiKeyRequestSchema: GenMessage<CreateApiKeyRequest, {jsonType: CreateApiKeyRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 1);

/**
 * CreateApiKeyResponse результат создания ключа.
 *
 * @generated from message emh.v1.CreateApiKeyResponse
 */
export type CreateApiKeyResponse = Message<"emh.v1.CreateApiKeyResponse"> & {
  /**
   * api_key - метаданные созданного ключа.
   *
   * @generated from field: emh.v1.ApiKey api_key = 1;
   */
  apiKey?: ApiKey | undefined;

  /**
   * full_key - полный ключ. Показывается ТОЛЬКО ОДИН РАЗ — сохраните его.
   *
   * @generated from field: string full_key = 2;
   */
  fullKey: string;
};

/**
 * CreateApiKeyResponse результат создания ключа.
 *
 * @generated from message emh.v1.CreateApiKeyResponse
 */
export type CreateApiKeyResponseJson = {
  /**
   * api_key - метаданные созданного ключа.
   *
   * @generated from field: emh.v1.ApiKey api_key = 1;
   */
  apiKey?: ApiKeyJson;

  /**
   * full_key - полный ключ. Показывается ТОЛЬКО ОДИН РАЗ — сохраните его.
   *
   * @generated from field: string full_key = 2;
   */
  fullKey?: string;
};

/**
 * Describes the message emh.v1.CreateApiKeyResponse.
 * Use `create(CreateApiKeyResponseSchema)` to create a new message.
 */
export const CreateApiKeyResponseSchema: GenMessage<CreateApiKeyResponse, {jsonType: CreateApiKeyResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 2);

/**
 * ListApiKeysRequest запрос списка ключей.
 *
 * @generated from message emh.v1.ListApiKeysRequest
 */
export type ListApiKeysRequest = Message<"emh.v1.ListApiKeysRequest"> & {
  /**
   * include_revoked - включать ли отозванные ключи.
   *
   * @generated from field: bool include_revoked = 1;
   */
  includeRevoked: boolean;
};

/**
 * ListApiKeysRequest запрос списка ключей.
 *
 * @generated from message emh.v1.ListApiKeysRequest
 */
export type ListApiKeysRequestJson = {
  /**
   * include_revoked - включать ли отозванные ключи.
   *
   * @generated from field: bool include_revoked = 1;
   */
  includeRevoked?: boolean;
};

/**
 * Describes the message emh.v1.ListApiKeysRequest.
 * Use `create(ListApiKeysRequestSchema)` to create a new message.
 */
export const ListApiKeysRequestSchema: GenMessage<ListApiKeysRequest, {jsonType: ListApiKeysRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 3);

/**
 * ListApiKeysResponse список ключей.
 *
 * @generated from message emh.v1.ListApiKeysResponse
 */
export type ListApiKeysResponse = Message<"emh.v1.ListApiKeysResponse"> & {
  /**
   * api_keys - массив ключей (без секретов).
   *
   * @generated from field: repeated emh.v1.ApiKey api_keys = 1;
   */
  apiKeys: ApiKey[];
};

/**
 * ListApiKeysResponse список ключей.
 *
 * @generated from message emh.v1.ListApiKeysResponse
 */
export type ListApiKeysResponseJson = {
  /**
   * api_keys - массив ключей (без секретов).
   *
   * @generated from field: repeated emh.v1.ApiKey api_keys = 1;
   */
  apiKeys?: ApiKeyJson[];
};

/**
 * Describes the message emh.v1.ListApiKeysResponse.
 * Use `create(ListApiKeysResponseSchema)` to create a new message.
 */
export const ListApiKeysResponseSchema: GenMessage<ListApiKeysResponse, {jsonType: ListApiKeysResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 4);

/**
 * RevokeApiKeyRequest запрос на отзыв ключа.
 *
 * @generated from message emh.v1.RevokeApiKeyRequest
 */
export type RevokeApiKeyRequest = Message<"emh.v1.RevokeApiKeyRequest"> & {
  /**
   * id - UUID отзывааемого ключа.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * RevokeApiKeyRequest запрос на отзыв ключа.
 *
 * @generated from message emh.v1.RevokeApiKeyRequest
 */
export type RevokeApiKeyRequestJson = {
  /**
   * id - UUID отзывааемого ключа.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.RevokeApiKeyRequest.
 * Use `create(RevokeApiKeyRequestSchema)` to create a new message.
 */
export const RevokeApiKeyRequestSchema: GenMessage<RevokeApiKeyRequest, {jsonType: RevokeApiKeyRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 5);

/**
 * RevokeApiKeyResponse подтверждение отзыва.
 *
 * @generated from message emh.v1.RevokeApiKeyResponse
 */
export type RevokeApiKeyResponse = Message<"emh.v1.RevokeApiKeyResponse"> & {
  /**
   * success - true если ключ отозван.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * RevokeApiKeyResponse подтверждение отзыва.
 *
 * @generated from message emh.v1.RevokeApiKeyResponse
 */
export type RevokeApiKeyResponseJson = {
  /**
   * success - true если ключ отозван.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.RevokeApiKeyResponse.
 * Use `create(RevokeApiKeyResponseSchema)` to create a new message.
 */
export const RevokeApiKeyResponseSchema: GenMessage<RevokeApiKeyResponse, {jsonType: RevokeApiKeyResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_api_key_admin, 6);

/**
 * ApiKeyAdminService защищённый сервис управления API-ключами.
 *
 * @generated from service emh.v1.ApiKeyAdminService
 */
export const ApiKeyAdminService: GenService<{
  /**
   * CreateApiKey создаёт ключ и возвращает его полное значение (один раз).
   *
   * @generated from rpc emh.v1.ApiKeyAdminService.CreateApiKey
   */
  createApiKey: {
    methodKind: "unary";
    input: typeof CreateApiKeyRequestSchema;
    output: typeof CreateApiKeyResponseSchema;
  },
  /**
   * ListApiKeys возвращает список ключей с их статусами.
   *
   * @generated from rpc emh.v1.ApiKeyAdminService.ListApiKeys
   */
  listApiKeys: {
    methodKind: "unary";
    input: typeof ListApiKeysRequestSchema;
    output: typeof ListApiKeysResponseSchema;
  },
  /**
   * RevokeApiKey отзывает ключ (без возможности восстановления).
   *
   * @generated from rpc emh.v1.ApiKeyAdminService.RevokeApiKey
   */
  revokeApiKey: {
    methodKind: "unary";
    input: typeof RevokeApiKeyRequestSchema;
    output: typeof RevokeApiKeyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_api_key_admin, 0);

