// Сервис аутентификации администраторов.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/auth.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/auth.proto.
 */
export const file_emh_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChFlbWgvdjEvYXV0aC5wcm90bxIGZW1oLnYxIkQKDExvZ2luUmVxdWVzdBIZCgh1c2VybmFtZRgBIAEoCUIHukgEcgIQARIZCghwYXNzd29yZBgCIAEoCUIHukgEcgIQASJ4Cg1Mb2dpblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRISCgp0b2tlbl90eXBlGAIgASgJEhIKCmV4cGlyZXNfYXQYAyABKAkSFQoNcmVmcmVzaF90b2tlbhgEIAEoCRISCgpleHBpcmVzX2luGAUgASgDIjUKE1JlZnJlc2hUb2tlblJlcXVlc3QSHgoNcmVmcmVzaF90b2tlbhgBIAEoCUIHukgEcgIQASJ/ChRSZWZyZXNoVG9rZW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSEgoKdG9rZW5fdHlwZRgCIAEoCRISCgpleHBpcmVzX2F0GAMgASgJEhUKDXJlZnJlc2hfdG9rZW4YBCABKAkSEgoKZXhwaXJlc19pbhgFIAEoAyIvCg1Mb2dvdXRSZXF1ZXN0Eh4KDXJlZnJlc2hfdG9rZW4YASABKAlCB7pIBHICEAEiIQoOTG9nb3V0UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCDLCAQoLQXV0aFNlcnZpY2USNAoFTG9naW4SFC5lbWgudjEuTG9naW5SZXF1ZXN0GhUuZW1oLnYxLkxvZ2luUmVzcG9uc2USRAoHUmVmcmVzaBIbLmVtaC52MS5SZWZyZXNoVG9rZW5SZXF1ZXN0GhwuZW1oLnYxLlJlZnJlc2hUb2tlblJlc3BvbnNlEjcKBkxvZ291dBIVLmVtaC52MS5Mb2dvdXRSZXF1ZXN0GhYuZW1oLnYxLkxvZ291dFJlc3BvbnNlQj1aO2NvZGViZXJnLm9yZy9UaHIwVFQxZS9lbWgvYmFja2VuZC9pbnRlcm5hbC9nZW4vZW1oL3YxO2VtaHYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * LoginRequest запрос на аутентификацию администратора.
 *
 * @generated from message emh.v1.LoginRequest
 */
export type LoginRequest = Message<"emh.v1.LoginRequest"> & {
  /**
   * username - имя пользователя (обязательно).
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * password - пароль (обязательно).
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * LoginRequest запрос на аутентификацию администратора.
 *
 * @generated from message emh.v1.LoginRequest
 */
export type LoginRequestJson = {
  /**
   * username - имя пользователя (обязательно).
   *
   * @generated from field: string username = 1;
   */
  username?: string;

  /**
   * password - пароль (обязательно).
   *
   * @generated from field: string password = 2;
   */
  password?: string;
};

/**
 * Describes the message emh.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest, {jsonType: LoginRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 0);

/**
 * LoginResponse результат успешной аутентификации.
 *
 * @generated from message emh.v1.LoginResponse
 */
export type LoginResponse = Message<"emh.v1.LoginResponse"> & {
  /**
   * access_token - JWT для запросов к админским сервисам.
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * token_type - тип токена (Bearer).
   *
   * @generated from field: string token_type = 2;
   */
  tokenType: string;

  /**
   * expires_at - время истечения access-токена (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt: string;

  /**
   * refresh_token - токен для получения новой пары access/refresh.
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * expires_in - время жизни access-токена в секундах.
   *
   * @generated from field: int64 expires_in = 5;
   */
  expiresIn: bigint;
};

/**
 * LoginResponse результат успешной аутентификации.
 *
 * @generated from message emh.v1.LoginResponse
 */
export type LoginResponseJson = {
  /**
   * access_token - JWT для запросов к админским сервисам.
   *
   * @generated from field: string access_token = 1;
   */
  accessToken?: string;

  /**
   * token_type - тип токена (Bearer).
   *
   * @generated from field: string token_type = 2;
   */
  tokenType?: string;

  /**
   * expires_at - время истечения access-токена (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt?: string;

  /**
   * refresh_token - токен для получения новой пары access/refresh.
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken?: string;

  /**
   * expires_in - время жизни access-токена в секундах.
   *
   * @generated from field: int64 expires_in = 5;
   */
  expiresIn?: string;
};

/**
 * Describes the message emh.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse, {jsonType: LoginResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 1);

/**
 * RefreshTokenRequest запрос на обновление токенов.
 *
 * @generated from message emh.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"emh.v1.RefreshTokenRequest"> & {
  /**
   * refresh_token - действующий refresh-токен.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * RefreshTokenRequest запрос на обновление токенов.
 *
 * @generated from message emh.v1.RefreshTokenRequest
 */
export type RefreshTokenRequestJson = {
  /**
   * refresh_token - действующий refresh-токен.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken?: string;
};

/**
 * Describes the message emh.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest, {jsonType: RefreshTokenRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 2);

/**
 * RefreshTokenResponse новая пара токенов после ротации.
 *
 * @generated from message emh.v1.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"emh.v1.RefreshTokenResponse"> & {
  /**
   * access_token - новый JWT.
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * token_type - тип токена (Bearer).
   *
   * @generated from field: string token_type = 2;
   */
  tokenType: string;

  /**
   * expires_at - время истечения access-токена (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt: string;

  /**
   * refresh_token - новый refresh-токен (старый отозван).
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * expires_in - время жизни access-токена в секундах.
   *
   * @generated from field: int64 expires_in = 5;
   */
  expiresIn: bigint;
};

/**
 * RefreshTokenResponse новая пара токенов после ротации.
 *
 * @generated from message emh.v1.RefreshTokenResponse
 */
export type RefreshTokenResponseJson = {
  /**
   * access_token - новый JWT.
   *
   * @generated from field: string access_token = 1;
   */
  accessToken?: string;

  /**
   * token_type - тип токена (Bearer).
   *
   * @generated from field: string token_type = 2;
   */
  tokenType?: string;

  /**
   * expires_at - время истечения access-токена (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt?: string;

  /**
   * refresh_token - новый refresh-токен (старый отозван).
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken?: string;

  /**
   * expires_in - время жизни access-токена в секундах.
   *
   * @generated from field: int64 expires_in = 5;
   */
  expiresIn?: string;
};

/**
 * Describes the message emh.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse, {jsonType: RefreshTokenResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 3);

/**
 * LogoutRequest запрос на отзыв refresh-токена.
 *
 * @generated from message emh.v1.LogoutRequest
 */
export type LogoutRequest = Message<"emh.v1.LogoutRequest"> & {
  /**
   * refresh_token - токен для отзыва.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * LogoutRequest запрос на отзыв refresh-токена.
 *
 * @generated from message emh.v1.LogoutRequest
 */
export type LogoutRequestJson = {
  /**
   * refresh_token - токен для отзыва.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken?: string;
};

/**
 * Describes the message emh.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest, {jsonType: LogoutRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 4);

/**
 * LogoutResponse результат выхода из системы.
 *
 * @generated from message emh.v1.LogoutResponse
 */
export type LogoutResponse = Message<"emh.v1.LogoutResponse"> & {
  /**
   * success - true если токен успешно отозван.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * LogoutResponse результат выхода из системы.
 *
 * @generated from message emh.v1.LogoutResponse
 */
export type LogoutResponseJson = {
  /**
   * success - true если токен успешно отозван.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse, {jsonType: LogoutResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_auth, 5);

/**
 * AuthService публичный сервис аутентификации (точка входа, не защищён).
 *
 * @generated from service emh.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Login выдаёт пару access/refresh токенов при успешной проверке учётных данных.
   *
   * @generated from rpc emh.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Refresh обменивает действующий refresh-токен на новую пару access/refresh.
   *
   * @generated from rpc emh.v1.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
  /**
   * Logout отзывает refresh-токен (выход из системы).
   *
   * @generated from rpc emh.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_auth, 0);

