// Административный сервис для управления справочником наград.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/award_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Award, AwardJson } from "./award_pb";
import { file_emh_v1_award } from "./award_pb";
import type { AwardJurisdiction, AwardJurisdictionJson, AwardType, AwardTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/award_admin.proto.
 */
export const file_emh_v1_award_admin: GenFile = /*@__PURE__*/
  fileDesc("ChhlbWgvdjEvYXdhcmRfYWRtaW4ucHJvdG8SBmVtaC52MSKrAgoSQ3JlYXRlQXdhcmRSZXF1ZXN0EhUKBG5hbWUYASABKAlCB7pIBHICEAESEwoLZGVzY3JpcHRpb24YAiABKAkSGwoJaW1hZ2VfdXJsGAMgASgJQgi6SAVyA4gBARIbCgpzb3J0X29yZGVyGAQgASgFQge6SAQaAigAEiUKEHJpYmJvbl9pbWFnZV91cmwYBSABKAlCC7pICNgBAXIDiAEBEikKBHR5cGUYBiABKA4yES5lbWgudjEuQXdhcmRUeXBlQgi6SAWCAQIgABIYChB3b3JuX3dpdGhvdXRfYmFyGAcgASgIEhIKCmlzX2p1YmlsZWUYCCABKAgSLwoManVyaXNkaWN0aW9uGAkgASgOMhkuZW1oLnYxLkF3YXJkSnVyaXNkaWN0aW9uIiEKE0NyZWF0ZUF3YXJkUmVzcG9uc2USCgoCaWQYASABKAki+QIKElVwZGF0ZUF3YXJkUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOwAQESGAoEbmFtZRgCIAEoCUIKukgHcgIQAdgBARITCgtkZXNjcmlwdGlvbhgDIAEoCRIeCglpbWFnZV91cmwYBCABKAlCC7pICHIDiAEB2AEBEh4KCnNvcnRfb3JkZXIYBSABKAVCCrpIBxoCKADYAQESEgoKZmllbGRfbWFzaxgGIAMoCRIlChByaWJib25faW1hZ2VfdXJsGAcgASgJQgu6SAhyA4gBAdgBARIsCgR0eXBlGAggASgOMhEuZW1oLnYxLkF3YXJkVHlwZUILukgI2AEBggECIAASIAoQd29ybl93aXRob3V0X2JhchgJIAEoCEIGukgD2AEBEhoKCmlzX2p1YmlsZWUYCiABKAhCBrpIA9gBARI3CgxqdXJpc2RpY3Rpb24YCyABKA4yGS5lbWgudjEuQXdhcmRKdXJpc2RpY3Rpb25CBrpIA9gBASIzChNVcGRhdGVBd2FyZFJlc3BvbnNlEhwKBWF3YXJkGAEgASgLMg0uZW1oLnYxLkF3YXJkIioKEkRlbGV0ZUF3YXJkUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOwAQEiJgoTRGVsZXRlQXdhcmRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIMusBChFBd2FyZEFkbWluU2VydmljZRJGCgtDcmVhdGVBd2FyZBIaLmVtaC52MS5DcmVhdGVBd2FyZFJlcXVlc3QaGy5lbWgudjEuQ3JlYXRlQXdhcmRSZXNwb25zZRJGCgtVcGRhdGVBd2FyZBIaLmVtaC52MS5VcGRhdGVBd2FyZFJlcXVlc3QaGy5lbWgudjEuVXBkYXRlQXdhcmRSZXNwb25zZRJGCgtEZWxldGVBd2FyZBIaLmVtaC52MS5EZWxldGVBd2FyZFJlcXVlc3QaGy5lbWgudjEuRGVsZXRlQXdhcmRSZXNwb25zZUI9Wjtjb2RlYmVyZy5vcmcvVGhyMFRUMWUvZW1oL2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2VtaC92MTtlbWh2MWIGcHJvdG8z", [file_emh_v1_award, file_emh_v1_enums_emh, file_buf_validate_validate]);

/**
 * CreateAwardRequest данные для создания новой награды в справочнике.
 *
 * @generated from message emh.v1.CreateAwardRequest
 */
export type CreateAwardRequest = Message<"emh.v1.CreateAwardRequest"> & {
  /**
   * name - официальное название награды (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * description - описание или статут награды.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * image_url - URL загруженного изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;

  /**
   * sort_order - приоритет сортировки при отображении (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 4;
   */
  sortOrder: number;

  /**
   * ribbon_image_url - URL изображения ленты награды для орденской планки.
   * Опционально: награду можно создать без загруженной ленты.
   *
   * @generated from field: string ribbon_image_url = 5;
   */
  ribbonImageUrl: string;

  /**
   * type - тип награды (орден, медаль, знак). Обязателен при создании.
   *
   * @generated from field: emh.v1.AwardType type = 6;
   */
  type: AwardType;

  /**
   * worn_without_bar - награда носится без колодки и не входит в блок планок.
   *
   * @generated from field: bool worn_without_bar = 7;
   */
  wornWithoutBar: boolean;

  /**
   * is_jubilee - признак юбилейной награды.
   *
   * @generated from field: bool is_jubilee = 8;
   */
  isJubilee: boolean;

  /**
   * jurisdiction - государственная принадлежность награды (РФ, СССР, ведомственная).
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 9;
   */
  jurisdiction: AwardJurisdiction;
};

/**
 * CreateAwardRequest данные для создания новой награды в справочнике.
 *
 * @generated from message emh.v1.CreateAwardRequest
 */
export type CreateAwardRequestJson = {
  /**
   * name - официальное название награды (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * description - описание или статут награды.
   *
   * @generated from field: string description = 2;
   */
  description?: string;

  /**
   * image_url - URL загруженного изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 3;
   */
  imageUrl?: string;

  /**
   * sort_order - приоритет сортировки при отображении (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 4;
   */
  sortOrder?: number;

  /**
   * ribbon_image_url - URL изображения ленты награды для орденской планки.
   * Опционально: награду можно создать без загруженной ленты.
   *
   * @generated from field: string ribbon_image_url = 5;
   */
  ribbonImageUrl?: string;

  /**
   * type - тип награды (орден, медаль, знак). Обязателен при создании.
   *
   * @generated from field: emh.v1.AwardType type = 6;
   */
  type?: AwardTypeJson;

  /**
   * worn_without_bar - награда носится без колодки и не входит в блок планок.
   *
   * @generated from field: bool worn_without_bar = 7;
   */
  wornWithoutBar?: boolean;

  /**
   * is_jubilee - признак юбилейной награды.
   *
   * @generated from field: bool is_jubilee = 8;
   */
  isJubilee?: boolean;

  /**
   * jurisdiction - государственная принадлежность награды (РФ, СССР, ведомственная).
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 9;
   */
  jurisdiction?: AwardJurisdictionJson;
};

/**
 * Describes the message emh.v1.CreateAwardRequest.
 * Use `create(CreateAwardRequestSchema)` to create a new message.
 */
export const CreateAwardRequestSchema: GenMessage<CreateAwardRequest, {jsonType: CreateAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 0);

/**
 * CreateAwardResponse результат успешного создания награды.
 *
 * @generated from message emh.v1.CreateAwardResponse
 */
export type CreateAwardResponse = Message<"emh.v1.CreateAwardResponse"> & {
  /**
   * id - UUID созданной награды.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * CreateAwardResponse результат успешного создания награды.
 *
 * @generated from message emh.v1.CreateAwardResponse
 */
export type CreateAwardResponseJson = {
  /**
   * id - UUID созданной награды.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.CreateAwardResponse.
 * Use `create(CreateAwardResponseSchema)` to create a new message.
 */
export const CreateAwardResponseSchema: GenMessage<CreateAwardResponse, {jsonType: CreateAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 1);

/**
 * UpdateAwardRequest данные для частичного обновления существующей награды.
 *
 * @generated from message emh.v1.UpdateAwardRequest
 */
export type UpdateAwardRequest = Message<"emh.v1.UpdateAwardRequest"> & {
  /**
   * id - UUID обновляемой награды (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - новое официальное название.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description - новое описание или статут.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * image_url - новый URL изображения награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;

  /**
   * sort_order - новый приоритет сортировки.
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder: number;

  /**
   * field_mask - список полей для обновления. Позволяет отличить очистку поля от отсутствия изменений.
   *
   * @generated from field: repeated string field_mask = 6;
   */
  fieldMask: string[];

  /**
   * ribbon_image_url - новый URL изображения ленты награды. Пустое значение очищает ленту.
   *
   * @generated from field: string ribbon_image_url = 7;
   */
  ribbonImageUrl: string;

  /**
   * type - новый тип награды (орден, медаль, знак).
   *
   * @generated from field: emh.v1.AwardType type = 8;
   */
  type: AwardType;

  /**
   * worn_without_bar - новый признак ношения без колодки.
   *
   * @generated from field: bool worn_without_bar = 9;
   */
  wornWithoutBar: boolean;

  /**
   * is_jubilee - новый признак юбилейной награды.
   *
   * @generated from field: bool is_jubilee = 10;
   */
  isJubilee: boolean;

  /**
   * jurisdiction - новая государственная принадлежность награды.
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 11;
   */
  jurisdiction: AwardJurisdiction;
};

/**
 * UpdateAwardRequest данные для частичного обновления существующей награды.
 *
 * @generated from message emh.v1.UpdateAwardRequest
 */
export type UpdateAwardRequestJson = {
  /**
   * id - UUID обновляемой награды (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - новое официальное название.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * description - новое описание или статут.
   *
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * image_url - новый URL изображения награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl?: string;

  /**
   * sort_order - новый приоритет сортировки.
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder?: number;

  /**
   * field_mask - список полей для обновления. Позволяет отличить очистку поля от отсутствия изменений.
   *
   * @generated from field: repeated string field_mask = 6;
   */
  fieldMask?: string[];

  /**
   * ribbon_image_url - новый URL изображения ленты награды. Пустое значение очищает ленту.
   *
   * @generated from field: string ribbon_image_url = 7;
   */
  ribbonImageUrl?: string;

  /**
   * type - новый тип награды (орден, медаль, знак).
   *
   * @generated from field: emh.v1.AwardType type = 8;
   */
  type?: AwardTypeJson;

  /**
   * worn_without_bar - новый признак ношения без колодки.
   *
   * @generated from field: bool worn_without_bar = 9;
   */
  wornWithoutBar?: boolean;

  /**
   * is_jubilee - новый признак юбилейной награды.
   *
   * @generated from field: bool is_jubilee = 10;
   */
  isJubilee?: boolean;

  /**
   * jurisdiction - новая государственная принадлежность награды.
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 11;
   */
  jurisdiction?: AwardJurisdictionJson;
};

/**
 * Describes the message emh.v1.UpdateAwardRequest.
 * Use `create(UpdateAwardRequestSchema)` to create a new message.
 */
export const UpdateAwardRequestSchema: GenMessage<UpdateAwardRequest, {jsonType: UpdateAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 2);

/**
 * UpdateAwardResponse обновленный объект награды.
 *
 * @generated from message emh.v1.UpdateAwardResponse
 */
export type UpdateAwardResponse = Message<"emh.v1.UpdateAwardResponse"> & {
  /**
   * award - актуальное состояние награды после обновления.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: Award | undefined;
};

/**
 * UpdateAwardResponse обновленный объект награды.
 *
 * @generated from message emh.v1.UpdateAwardResponse
 */
export type UpdateAwardResponseJson = {
  /**
   * award - актуальное состояние награды после обновления.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: AwardJson;
};

/**
 * Describes the message emh.v1.UpdateAwardResponse.
 * Use `create(UpdateAwardResponseSchema)` to create a new message.
 */
export const UpdateAwardResponseSchema: GenMessage<UpdateAwardResponse, {jsonType: UpdateAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 3);

/**
 * DeleteAwardRequest запрос на удаление награды из справочника.
 *
 * @generated from message emh.v1.DeleteAwardRequest
 */
export type DeleteAwardRequest = Message<"emh.v1.DeleteAwardRequest"> & {
  /**
   * id - UUID удаляемой награды.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * DeleteAwardRequest запрос на удаление награды из справочника.
 *
 * @generated from message emh.v1.DeleteAwardRequest
 */
export type DeleteAwardRequestJson = {
  /**
   * id - UUID удаляемой награды.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.DeleteAwardRequest.
 * Use `create(DeleteAwardRequestSchema)` to create a new message.
 */
export const DeleteAwardRequestSchema: GenMessage<DeleteAwardRequest, {jsonType: DeleteAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 4);

/**
 * DeleteAwardResponse подтверждение операции удаления.
 *
 * @generated from message emh.v1.DeleteAwardResponse
 */
export type DeleteAwardResponse = Message<"emh.v1.DeleteAwardResponse"> & {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * DeleteAwardResponse подтверждение операции удаления.
 *
 * @generated from message emh.v1.DeleteAwardResponse
 */
export type DeleteAwardResponseJson = {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.DeleteAwardResponse.
 * Use `create(DeleteAwardResponseSchema)` to create a new message.
 */
export const DeleteAwardResponseSchema: GenMessage<DeleteAwardResponse, {jsonType: DeleteAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 5);

/**
 * AwardAdminService защищенный сервис для управления справочником наград.
 *
 * @generated from service emh.v1.AwardAdminService
 */
export const AwardAdminService: GenService<{
  /**
   * CreateAward создает новую запись в справочнике наград.
   *
   * @generated from rpc emh.v1.AwardAdminService.CreateAward
   */
  createAward: {
    methodKind: "unary";
    input: typeof CreateAwardRequestSchema;
    output: typeof CreateAwardResponseSchema;
  },
  /**
   * UpdateAward частично обновляет существующую награду по field_mask.
   *
   * @generated from rpc emh.v1.AwardAdminService.UpdateAward
   */
  updateAward: {
    methodKind: "unary";
    input: typeof UpdateAwardRequestSchema;
    output: typeof UpdateAwardResponseSchema;
  },
  /**
   * DeleteAward удаляет награду. При наличии связей с героями вернет ошибку.
   *
   * @generated from rpc emh.v1.AwardAdminService.DeleteAward
   */
  deleteAward: {
    methodKind: "unary";
    input: typeof DeleteAwardRequestSchema;
    output: typeof DeleteAwardResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_award_admin, 0);

