// Справочник наград. Необходим для отображения названий и изображений наград в карточке героя.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/award.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AwardJurisdiction, AwardJurisdictionJson, AwardType, AwardTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { PaginationRequest, PaginationRequestJson, PaginationResponse, PaginationResponseJson } from "./common_pb";
import { file_emh_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/award.proto.
 */
export const file_emh_v1_award: GenFile = /*@__PURE__*/
  fileDesc("ChJlbWgvdjEvYXdhcmQucHJvdG8SBmVtaC52MSL3AQoFQXdhcmQSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIRCglpbWFnZV91cmwYBCABKAkSEgoKc29ydF9vcmRlchgFIAEoBRIYChByaWJib25faW1hZ2VfdXJsGAYgASgJEh8KBHR5cGUYByABKA4yES5lbWgudjEuQXdhcmRUeXBlEhgKEHdvcm5fd2l0aG91dF9iYXIYCCABKAgSEgoKaXNfanViaWxlZRgJIAEoCBIvCgxqdXJpc2RpY3Rpb24YCiABKA4yGS5lbWgudjEuQXdhcmRKdXJpc2RpY3Rpb24iHQoPR2V0QXdhcmRSZXF1ZXN0EgoKAmlkGAEgASgJIjAKEEdldEF3YXJkUmVzcG9uc2USHAoFYXdhcmQYASABKAsyDS5lbWgudjEuQXdhcmQiWAoRTGlzdEF3YXJkc1JlcXVlc3QSFAoMc2VhcmNoX3F1ZXJ5GAEgASgJEi0KCnBhZ2luYXRpb24YAiABKAsyGS5lbWgudjEuUGFnaW5hdGlvblJlcXVlc3QiYwoSTGlzdEF3YXJkc1Jlc3BvbnNlEh0KBmF3YXJkcxgBIAMoCzINLmVtaC52MS5Bd2FyZBIuCgpwYWdpbmF0aW9uGAIgASgLMhouZW1oLnYxLlBhZ2luYXRpb25SZXNwb25zZTKSAQoMQXdhcmRTZXJ2aWNlEj0KCEdldEF3YXJkEhcuZW1oLnYxLkdldEF3YXJkUmVxdWVzdBoYLmVtaC52MS5HZXRBd2FyZFJlc3BvbnNlEkMKCkxpc3RBd2FyZHMSGS5lbWgudjEuTGlzdEF3YXJkc1JlcXVlc3QaGi5lbWgudjEuTGlzdEF3YXJkc1Jlc3BvbnNlQj1aO2NvZGViZXJnLm9yZy9UaHIwVFQxZS9lbWgvYmFja2VuZC9pbnRlcm5hbC9nZW4vZW1oL3YxO2VtaHYxYgZwcm90bzM", [file_emh_v1_enums_emh, file_emh_v1_common]);

/**
 * Award представляет государственную или ведомственную награду.
 *
 * @generated from message emh.v1.Award
 */
export type Award = Message<"emh.v1.Award"> & {
  /**
   * id - уникальный идентификатор награды (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - официальное название награды.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description - краткое описание или статут награды.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * image_url - URL изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;

  /**
   * sort_order - приоритет отображения (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder: number;

  /**
   * ribbon_image_url - URL изображения ленты награды для орденской планки.
   *
   * @generated from field: string ribbon_image_url = 6;
   */
  ribbonImageUrl: string;

  /**
   * type - тип награды (орден, медаль, знак).
   * Влияет на старшинство согласно приказу МО РФ №1500.
   *
   * @generated from field: emh.v1.AwardType type = 7;
   */
  type: AwardType;

  /**
   * worn_without_bar - награда носится без колодки (звёзды орденов, знаки).
   * Такие награды не включаются в общий блок планок.
   *
   * @generated from field: bool worn_without_bar = 8;
   */
  wornWithoutBar: boolean;

  /**
   * is_jubilee - юбилейная награда (влияет на старшинство: боевые выше юбилейных).
   *
   * @generated from field: bool is_jubilee = 9;
   */
  isJubilee: boolean;

  /**
   * jurisdiction - государственная принадлежность награды (РФ, СССР, ведомственная).
   * Первичная ось старшинства в орденской планке.
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 10;
   */
  jurisdiction: AwardJurisdiction;
};

/**
 * Award представляет государственную или ведомственную награду.
 *
 * @generated from message emh.v1.Award
 */
export type AwardJson = {
  /**
   * id - уникальный идентификатор награды (UUID).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - официальное название награды.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * description - краткое описание или статут награды.
   *
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * image_url - URL изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl?: string;

  /**
   * sort_order - приоритет отображения (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder?: number;

  /**
   * ribbon_image_url - URL изображения ленты награды для орденской планки.
   *
   * @generated from field: string ribbon_image_url = 6;
   */
  ribbonImageUrl?: string;

  /**
   * type - тип награды (орден, медаль, знак).
   * Влияет на старшинство согласно приказу МО РФ №1500.
   *
   * @generated from field: emh.v1.AwardType type = 7;
   */
  type?: AwardTypeJson;

  /**
   * worn_without_bar - награда носится без колодки (звёзды орденов, знаки).
   * Такие награды не включаются в общий блок планок.
   *
   * @generated from field: bool worn_without_bar = 8;
   */
  wornWithoutBar?: boolean;

  /**
   * is_jubilee - юбилейная награда (влияет на старшинство: боевые выше юбилейных).
   *
   * @generated from field: bool is_jubilee = 9;
   */
  isJubilee?: boolean;

  /**
   * jurisdiction - государственная принадлежность награды (РФ, СССР, ведомственная).
   * Первичная ось старшинства в орденской планке.
   *
   * @generated from field: emh.v1.AwardJurisdiction jurisdiction = 10;
   */
  jurisdiction?: AwardJurisdictionJson;
};

/**
 * Describes the message emh.v1.Award.
 * Use `create(AwardSchema)` to create a new message.
 */
export const AwardSchema: GenMessage<Award, {jsonType: AwardJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award, 0);

/**
 * GetAwardRequest запрос на получение награды по ID.
 *
 * @generated from message emh.v1.GetAwardRequest
 */
export type GetAwardRequest = Message<"emh.v1.GetAwardRequest"> & {
  /**
   * id - UUID награды.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * GetAwardRequest запрос на получение награды по ID.
 *
 * @generated from message emh.v1.GetAwardRequest
 */
export type GetAwardRequestJson = {
  /**
   * id - UUID награды.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.GetAwardRequest.
 * Use `create(GetAwardRequestSchema)` to create a new message.
 */
export const GetAwardRequestSchema: GenMessage<GetAwardRequest, {jsonType: GetAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award, 1);

/**
 * GetAwardResponse ответ с данными награды.
 *
 * @generated from message emh.v1.GetAwardResponse
 */
export type GetAwardResponse = Message<"emh.v1.GetAwardResponse"> & {
  /**
   * award - объект награды.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: Award | undefined;
};

/**
 * GetAwardResponse ответ с данными награды.
 *
 * @generated from message emh.v1.GetAwardResponse
 */
export type GetAwardResponseJson = {
  /**
   * award - объект награды.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: AwardJson;
};

/**
 * Describes the message emh.v1.GetAwardResponse.
 * Use `create(GetAwardResponseSchema)` to create a new message.
 */
export const GetAwardResponseSchema: GenMessage<GetAwardResponse, {jsonType: GetAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award, 2);

/**
 * ListAwardsRequest параметры выборки списка наград.
 *
 * @generated from message emh.v1.ListAwardsRequest
 */
export type ListAwardsRequest = Message<"emh.v1.ListAwardsRequest"> & {
  /**
   * search_query - поиск по названию награды.
   *
   * @generated from field: string search_query = 1;
   */
  searchQuery: string;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest | undefined;
};

/**
 * ListAwardsRequest параметры выборки списка наград.
 *
 * @generated from message emh.v1.ListAwardsRequest
 */
export type ListAwardsRequestJson = {
  /**
   * search_query - поиск по названию награды.
   *
   * @generated from field: string search_query = 1;
   */
  searchQuery?: string;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequestJson;
};

/**
 * Describes the message emh.v1.ListAwardsRequest.
 * Use `create(ListAwardsRequestSchema)` to create a new message.
 */
export const ListAwardsRequestSchema: GenMessage<ListAwardsRequest, {jsonType: ListAwardsRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award, 3);

/**
 * ListAwardsResponse список доступных наград.
 *
 * @generated from message emh.v1.ListAwardsResponse
 */
export type ListAwardsResponse = Message<"emh.v1.ListAwardsResponse"> & {
  /**
   * awards - массив объектов наград.
   *
   * @generated from field: repeated emh.v1.Award awards = 1;
   */
  awards: Award[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse | undefined;
};

/**
 * ListAwardsResponse список доступных наград.
 *
 * @generated from message emh.v1.ListAwardsResponse
 */
export type ListAwardsResponseJson = {
  /**
   * awards - массив объектов наград.
   *
   * @generated from field: repeated emh.v1.Award awards = 1;
   */
  awards?: AwardJson[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponseJson;
};

/**
 * Describes the message emh.v1.ListAwardsResponse.
 * Use `create(ListAwardsResponseSchema)` to create a new message.
 */
export const ListAwardsResponseSchema: GenMessage<ListAwardsResponse, {jsonType: ListAwardsResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award, 4);

/**
 * AwardService публичный сервис для чтения справочника наград.
 *
 * @generated from service emh.v1.AwardService
 */
export const AwardService: GenService<{
  /**
   * GetAward возвращает награду по ID.
   *
   * @generated from rpc emh.v1.AwardService.GetAward
   */
  getAward: {
    methodKind: "unary";
    input: typeof GetAwardRequestSchema;
    output: typeof GetAwardResponseSchema;
  },
  /**
   * ListAwards возвращает список всех наград (справочник обычно небольшой).
   *
   * @generated from rpc emh.v1.AwardService.ListAwards
   */
  listAwards: {
    methodKind: "unary";
    input: typeof ListAwardsRequestSchema;
    output: typeof ListAwardsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_award, 0);

