// Административный сервис для управления справочником наград.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/award_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Award, AwardJson } from "./award_pb";
import { file_emh_v1_award } from "./award_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/award_admin.proto.
 */
export const file_emh_v1_award_admin: GenFile = /*@__PURE__*/
  fileDesc("ChhlbWgvdjEvYXdhcmRfYWRtaW4ucHJvdG8SBmVtaC52MSJ6ChJDcmVhdGVBd2FyZFJlcXVlc3QSFQoEbmFtZRgBIAEoCUIHukgEcgIQARITCgtkZXNjcmlwdGlvbhgCIAEoCRIbCglpbWFnZV91cmwYAyABKAlCCLpIBXIDiAEBEhsKCnNvcnRfb3JkZXIYBCABKAVCB7pIBBoCKAAiIQoTQ3JlYXRlQXdhcmRSZXNwb25zZRIKCgJpZBgBIAEoCSKtAQoSVXBkYXRlQXdhcmRSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABARIYCgRuYW1lGAIgASgJQgq6SAdyAhAB2AEBEhMKC2Rlc2NyaXB0aW9uGAMgASgJEh4KCWltYWdlX3VybBgEIAEoCUILukgI2AEBcgOIAQESHgoKc29ydF9vcmRlchgFIAEoBUIKukgHGgIoANgBARISCgpmaWVsZF9tYXNrGAYgAygJIjMKE1VwZGF0ZUF3YXJkUmVzcG9uc2USHAoFYXdhcmQYASABKAsyDS5lbWgudjEuQXdhcmQiKgoSRGVsZXRlQXdhcmRSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABASImChNEZWxldGVBd2FyZFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy6wEKEUF3YXJkQWRtaW5TZXJ2aWNlEkYKC0NyZWF0ZUF3YXJkEhouZW1oLnYxLkNyZWF0ZUF3YXJkUmVxdWVzdBobLmVtaC52MS5DcmVhdGVBd2FyZFJlc3BvbnNlEkYKC1VwZGF0ZUF3YXJkEhouZW1oLnYxLlVwZGF0ZUF3YXJkUmVxdWVzdBobLmVtaC52MS5VcGRhdGVBd2FyZFJlc3BvbnNlEkYKC0RlbGV0ZUF3YXJkEhouZW1oLnYxLkRlbGV0ZUF3YXJkUmVxdWVzdBobLmVtaC52MS5EZWxldGVBd2FyZFJlc3BvbnNlQj1aO2NvZGViZXJnLm9yZy9UaHIwVFQxZS9lbWgvYmFja2VuZC9pbnRlcm5hbC9nZW4vZW1oL3YxO2VtaHYxYgZwcm90bzM", [file_emh_v1_award, file_buf_validate_validate]);

/**
 * CreateAwardRequest данные для создания новой награды в справочнике.
 *
 * @generated from message emh.v1.CreateAwardRequest
 */
export type CreateAwardRequest = Message<"emh.v1.CreateAwardRequest"> & {
  /**
   * name - официальное название награды (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * description - описание или статут награды.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * image_url - URL загруженного изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;

  /**
   * sort_order - приоритет сортировки при отображении (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 4;
   */
  sortOrder: number;
};

/**
 * CreateAwardRequest данные для создания новой награды в справочнике.
 *
 * @generated from message emh.v1.CreateAwardRequest
 */
export type CreateAwardRequestJson = {
  /**
   * name - официальное название награды (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * description - описание или статут награды.
   *
   * @generated from field: string description = 2;
   */
  description?: string;

  /**
   * image_url - URL загруженного изображения ленты или знака награды.
   *
   * @generated from field: string image_url = 3;
   */
  imageUrl?: string;

  /**
   * sort_order - приоритет сортировки при отображении (старшие награды выше).
   *
   * @generated from field: int32 sort_order = 4;
   */
  sortOrder?: number;
};

/**
 * Describes the message emh.v1.CreateAwardRequest.
 * Use `create(CreateAwardRequestSchema)` to create a new message.
 */
export const CreateAwardRequestSchema: GenMessage<CreateAwardRequest, {jsonType: CreateAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 0);

/**
 * CreateAwardResponse результат успешного создания награды.
 *
 * @generated from message emh.v1.CreateAwardResponse
 */
export type CreateAwardResponse = Message<"emh.v1.CreateAwardResponse"> & {
  /**
   * id - UUID созданной награды.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * CreateAwardResponse результат успешного создания награды.
 *
 * @generated from message emh.v1.CreateAwardResponse
 */
export type CreateAwardResponseJson = {
  /**
   * id - UUID созданной награды.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.CreateAwardResponse.
 * Use `create(CreateAwardResponseSchema)` to create a new message.
 */
export const CreateAwardResponseSchema: GenMessage<CreateAwardResponse, {jsonType: CreateAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 1);

/**
 * UpdateAwardRequest данные для частичного обновления существующей награды.
 *
 * @generated from message emh.v1.UpdateAwardRequest
 */
export type UpdateAwardRequest = Message<"emh.v1.UpdateAwardRequest"> & {
  /**
   * id - UUID обновляемой награды (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - новое официальное название.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description - новое описание или статут.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * image_url - новый URL изображения награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;

  /**
   * sort_order - новый приоритет сортировки.
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder: number;

  /**
   * field_mask - список полей для обновления. Позволяет отличить очистку поля от отсутствия изменений.
   *
   * @generated from field: repeated string field_mask = 6;
   */
  fieldMask: string[];
};

/**
 * UpdateAwardRequest данные для частичного обновления существующей награды.
 *
 * @generated from message emh.v1.UpdateAwardRequest
 */
export type UpdateAwardRequestJson = {
  /**
   * id - UUID обновляемой награды (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - новое официальное название.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * description - новое описание или статут.
   *
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * image_url - новый URL изображения награды.
   *
   * @generated from field: string image_url = 4;
   */
  imageUrl?: string;

  /**
   * sort_order - новый приоритет сортировки.
   *
   * @generated from field: int32 sort_order = 5;
   */
  sortOrder?: number;

  /**
   * field_mask - список полей для обновления. Позволяет отличить очистку поля от отсутствия изменений.
   *
   * @generated from field: repeated string field_mask = 6;
   */
  fieldMask?: string[];
};

/**
 * Describes the message emh.v1.UpdateAwardRequest.
 * Use `create(UpdateAwardRequestSchema)` to create a new message.
 */
export const UpdateAwardRequestSchema: GenMessage<UpdateAwardRequest, {jsonType: UpdateAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 2);

/**
 * UpdateAwardResponse обновленный объект награды.
 *
 * @generated from message emh.v1.UpdateAwardResponse
 */
export type UpdateAwardResponse = Message<"emh.v1.UpdateAwardResponse"> & {
  /**
   * award - актуальное состояние награды после обновления.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: Award | undefined;
};

/**
 * UpdateAwardResponse обновленный объект награды.
 *
 * @generated from message emh.v1.UpdateAwardResponse
 */
export type UpdateAwardResponseJson = {
  /**
   * award - актуальное состояние награды после обновления.
   *
   * @generated from field: emh.v1.Award award = 1;
   */
  award?: AwardJson;
};

/**
 * Describes the message emh.v1.UpdateAwardResponse.
 * Use `create(UpdateAwardResponseSchema)` to create a new message.
 */
export const UpdateAwardResponseSchema: GenMessage<UpdateAwardResponse, {jsonType: UpdateAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 3);

/**
 * DeleteAwardRequest запрос на удаление награды из справочника.
 *
 * @generated from message emh.v1.DeleteAwardRequest
 */
export type DeleteAwardRequest = Message<"emh.v1.DeleteAwardRequest"> & {
  /**
   * id - UUID удаляемой награды.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * DeleteAwardRequest запрос на удаление награды из справочника.
 *
 * @generated from message emh.v1.DeleteAwardRequest
 */
export type DeleteAwardRequestJson = {
  /**
   * id - UUID удаляемой награды.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.DeleteAwardRequest.
 * Use `create(DeleteAwardRequestSchema)` to create a new message.
 */
export const DeleteAwardRequestSchema: GenMessage<DeleteAwardRequest, {jsonType: DeleteAwardRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 4);

/**
 * DeleteAwardResponse подтверждение операции удаления.
 *
 * @generated from message emh.v1.DeleteAwardResponse
 */
export type DeleteAwardResponse = Message<"emh.v1.DeleteAwardResponse"> & {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * DeleteAwardResponse подтверждение операции удаления.
 *
 * @generated from message emh.v1.DeleteAwardResponse
 */
export type DeleteAwardResponseJson = {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.DeleteAwardResponse.
 * Use `create(DeleteAwardResponseSchema)` to create a new message.
 */
export const DeleteAwardResponseSchema: GenMessage<DeleteAwardResponse, {jsonType: DeleteAwardResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_award_admin, 5);

/**
 * AwardAdminService защищенный сервис для управления справочником наград.
 *
 * @generated from service emh.v1.AwardAdminService
 */
export const AwardAdminService: GenService<{
  /**
   * CreateAward создает новую запись в справочнике наград.
   *
   * @generated from rpc emh.v1.AwardAdminService.CreateAward
   */
  createAward: {
    methodKind: "unary";
    input: typeof CreateAwardRequestSchema;
    output: typeof CreateAwardResponseSchema;
  },
  /**
   * UpdateAward частично обновляет существующую награду по field_mask.
   *
   * @generated from rpc emh.v1.AwardAdminService.UpdateAward
   */
  updateAward: {
    methodKind: "unary";
    input: typeof UpdateAwardRequestSchema;
    output: typeof UpdateAwardResponseSchema;
  },
  /**
   * DeleteAward удаляет награду. При наличии связей с героями вернет ошибку.
   *
   * @generated from rpc emh.v1.AwardAdminService.DeleteAward
   */
  deleteAward: {
    methodKind: "unary";
    input: typeof DeleteAwardRequestSchema;
    output: typeof DeleteAwardResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_award_admin, 0);

