// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/common.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DatePrecision, DatePrecisionJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/common.proto.
 */
export const file_emh_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChNlbWgvdjEvY29tbW9uLnByb3RvEgZlbWgudjEiNgoRUGFnaW5hdGlvblJlcXVlc3QSDgoGY3Vyc29yGAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBSI+ChJQYWdpbmF0aW9uUmVzcG9uc2USEwoLbmV4dF9jdXJzb3IYASABKAkSEwoLdG90YWxfY291bnQYAiABKAMifwoJQXVkaXRJbmZvEi4KCmNyZWF0ZWRfYXQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhIKCmNyZWF0ZWRfYnkYAyABKAkikwEKDEZsZXhpYmxlRGF0ZRIvCgthbmNob3JfZGF0ZRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMgoJcHJlY2lzaW9uGAIgASgOMhUuZW1oLnYxLkRhdGVQcmVjaXNpb25CCLpIBYIBAiAAEh4KDGRpc3BsYXlfdGV4dBgDIAEoCUIIukgFcgMYyAFCPVo7Y29kZWJlcmcub3JnL1RocjBUVDFlL2VtaC9iYWNrZW5kL2ludGVybmFsL2dlbi9lbWgvdjE7ZW1odjFiBnByb3RvMw", [file_emh_v1_enums_emh, file_google_protobuf_timestamp, file_buf_validate_validate]);

/**
 * PaginationRequest параметры cursor-based пагинации для списков.
 *
 * @generated from message emh.v1.PaginationRequest
 */
export type PaginationRequest = Message<"emh.v1.PaginationRequest"> & {
  /**
   * cursor - непрозрачный курсор из предыдущего ответа. Пустая строка для первой страницы.
   *
   * @generated from field: string cursor = 1;
   */
  cursor: string;

  /**
   * page_size - количество элементов на странице. Максимум 100, по умолчанию 20.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;
};

/**
 * PaginationRequest параметры cursor-based пагинации для списков.
 *
 * @generated from message emh.v1.PaginationRequest
 */
export type PaginationRequestJson = {
  /**
   * cursor - непрозрачный курсор из предыдущего ответа. Пустая строка для первой страницы.
   *
   * @generated from field: string cursor = 1;
   */
  cursor?: string;

  /**
   * page_size - количество элементов на странице. Максимум 100, по умолчанию 20.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize?: number;
};

/**
 * Describes the message emh.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest, {jsonType: PaginationRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_common, 0);

/**
 * PaginationResponse метаданные пагинации для навигации по спискам.
 *
 * @generated from message emh.v1.PaginationResponse
 */
export type PaginationResponse = Message<"emh.v1.PaginationResponse"> & {
  /**
   * next_cursor - курсор следующей страницы. Пустая строка означает конец списка.
   *
   * @generated from field: string next_cursor = 1;
   */
  nextCursor: string;

  /**
   * total_count - общее количество найденных записей (опционально, может быть 0 если подсчет отключен).
   *
   * @generated from field: int64 total_count = 2;
   */
  totalCount: bigint;
};

/**
 * PaginationResponse метаданные пагинации для навигации по спискам.
 *
 * @generated from message emh.v1.PaginationResponse
 */
export type PaginationResponseJson = {
  /**
   * next_cursor - курсор следующей страницы. Пустая строка означает конец списка.
   *
   * @generated from field: string next_cursor = 1;
   */
  nextCursor?: string;

  /**
   * total_count - общее количество найденных записей (опционально, может быть 0 если подсчет отключен).
   *
   * @generated from field: int64 total_count = 2;
   */
  totalCount?: string;
};

/**
 * Describes the message emh.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse, {jsonType: PaginationResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_common, 1);

/**
 * AuditInfo системные метаданные записи для аудита и отслеживания изменений.
 *
 * @generated from message emh.v1.AuditInfo
 */
export type AuditInfo = Message<"emh.v1.AuditInfo"> & {
  /**
   * created_at - дата и время создания записи в UTC.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp | undefined;

  /**
   * updated_at - дата и время последнего обновления записи в UTC.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * created_by - идентификатор пользователя или системы, создавшей запись.
   *
   * @generated from field: string created_by = 3;
   */
  createdBy: string;
};

/**
 * AuditInfo системные метаданные записи для аудита и отслеживания изменений.
 *
 * @generated from message emh.v1.AuditInfo
 */
export type AuditInfoJson = {
  /**
   * created_at - дата и время создания записи в UTC.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: TimestampJson;

  /**
   * updated_at - дата и время последнего обновления записи в UTC.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: TimestampJson;

  /**
   * created_by - идентификатор пользователя или системы, создавшей запись.
   *
   * @generated from field: string created_by = 3;
   */
  createdBy?: string;
};

/**
 * Describes the message emh.v1.AuditInfo.
 * Use `create(AuditInfoSchema)` to create a new message.
 */
export const AuditInfoSchema: GenMessage<AuditInfo, {jsonType: AuditInfoJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_common, 2);

/**
 * FlexibleDate представляет гибкую дату с уровнем точности и текстовым представлением.
 *
 * @generated from message emh.v1.FlexibleDate
 */
export type FlexibleDate = Message<"emh.v1.FlexibleDate"> & {
  /**
   * anchor_date - опорная дата для сортировки и фильтрации.
   * Для точной даты это YYYY-MM-DD.
   * Для месяца - первое число месяца.
   * Для года - 1 января.
   * Для сезона - условная дата начала сезона.
   * Для DAY_MONTH и UNKNOWN должно быть пустым.
   *
   * @generated from field: google.protobuf.Timestamp anchor_date = 1;
   */
  anchorDate?: Timestamp | undefined;

  /**
   * precision - уровень точности даты.
   *
   * @generated from field: emh.v1.DatePrecision precision = 2;
   */
  precision: DatePrecision;

  /**
   * display_text - человекочитаемое представление даты из источника.
   * Например: "28 июля", "Февраль 1994", "Лето 1989".
   *
   * @generated from field: string display_text = 3;
   */
  displayText: string;
};

/**
 * FlexibleDate представляет гибкую дату с уровнем точности и текстовым представлением.
 *
 * @generated from message emh.v1.FlexibleDate
 */
export type FlexibleDateJson = {
  /**
   * anchor_date - опорная дата для сортировки и фильтрации.
   * Для точной даты это YYYY-MM-DD.
   * Для месяца - первое число месяца.
   * Для года - 1 января.
   * Для сезона - условная дата начала сезона.
   * Для DAY_MONTH и UNKNOWN должно быть пустым.
   *
   * @generated from field: google.protobuf.Timestamp anchor_date = 1;
   */
  anchorDate?: TimestampJson;

  /**
   * precision - уровень точности даты.
   *
   * @generated from field: emh.v1.DatePrecision precision = 2;
   */
  precision?: DatePrecisionJson;

  /**
   * display_text - человекочитаемое представление даты из источника.
   * Например: "28 июля", "Февраль 1994", "Лето 1989".
   *
   * @generated from field: string display_text = 3;
   */
  displayText?: string;
};

/**
 * Describes the message emh.v1.FlexibleDate.
 * Use `create(FlexibleDateSchema)` to create a new message.
 */
export const FlexibleDateSchema: GenMessage<FlexibleDate, {jsonType: FlexibleDateJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_common, 3);

