// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/conflict_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConflictType, ConflictTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { FlexibleDate, FlexibleDateJson } from "./common_pb";
import { file_emh_v1_common } from "./common_pb";
import type { Conflict, ConflictJson } from "./conflict_pb";
import { file_emh_v1_conflict } from "./conflict_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/conflict_admin.proto.
 */
export const file_emh_v1_conflict_admin: GenFile = /*@__PURE__*/
  fileDesc("ChtlbWgvdjEvY29uZmxpY3RfYWRtaW4ucHJvdG8SBmVtaC52MSLXAgoVQ3JlYXRlQ29uZmxpY3RSZXF1ZXN0EhUKBG5hbWUYASABKAlCB7pIBHICEAESEwoLZGVzY3JpcHRpb24YAiABKAkSLAoEdHlwZRgDIAEoDjIULmVtaC52MS5Db25mbGljdFR5cGVCCLpIBYIBAiAAEi4KCnN0YXJ0X2RhdGUYBCABKAlCGrpIF3IVMhNeXGR7NH0tXGR7Mn0tXGR7Mn0kEi8KCGVuZF9kYXRlGAUgASgJQh26SBpyGDIWXihcZHs0fS1cZHsyfS1cZHsyfXwpJBInChJwYXJlbnRfY29uZmxpY3RfaWQYBiABKAlCC7pICHIDsAEB2AEBEi0KD3N0YXJ0X2RhdGVfaW5mbxgHIAEoCzIULmVtaC52MS5GbGV4aWJsZURhdGUSKwoNZW5kX2RhdGVfaW5mbxgIIAEoCzIULmVtaC52MS5GbGV4aWJsZURhdGUiJAoWQ3JlYXRlQ29uZmxpY3RSZXNwb25zZRIKCgJpZBgBIAEoCSKdAwoVVXBkYXRlQ29uZmxpY3RSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABARIYCgRuYW1lGAIgASgJQgq6SAfYAQFyAhABEhMKC2Rlc2NyaXB0aW9uGAMgASgJEi8KBHR5cGUYBCABKA4yFC5lbWgudjEuQ29uZmxpY3RUeXBlQgu6SAiCAQIgANgBARIxCgpzdGFydF9kYXRlGAUgASgJQh26SBpyFTITXlxkezR9LVxkezJ9LVxkezJ9JNgBARIyCghlbmRfZGF0ZRgGIAEoCUIgukgdchgyFl4oXGR7NH0tXGR7Mn0tXGR7Mn18KSTYAQESJwoScGFyZW50X2NvbmZsaWN0X2lkGAcgASgJQgu6SAhyA7ABAdgBARISCgpmaWVsZF9tYXNrGAggAygJEjUKD3N0YXJ0X2RhdGVfaW5mbxgJIAEoCzIULmVtaC52MS5GbGV4aWJsZURhdGVCBrpIA9gBARIzCg1lbmRfZGF0ZV9pbmZvGAogASgLMhQuZW1oLnYxLkZsZXhpYmxlRGF0ZUIGukgD2AEBIjwKFlVwZGF0ZUNvbmZsaWN0UmVzcG9uc2USIgoIY29uZmxpY3QYASABKAsyEC5lbWgudjEuQ29uZmxpY3QiLQoVRGVsZXRlQ29uZmxpY3RSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABASIpChZEZWxldGVDb25mbGljdFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgyiQIKFENvbmZsaWN0QWRtaW5TZXJ2aWNlEk8KDkNyZWF0ZUNvbmZsaWN0Eh0uZW1oLnYxLkNyZWF0ZUNvbmZsaWN0UmVxdWVzdBoeLmVtaC52MS5DcmVhdGVDb25mbGljdFJlc3BvbnNlEk8KDlVwZGF0ZUNvbmZsaWN0Eh0uZW1oLnYxLlVwZGF0ZUNvbmZsaWN0UmVxdWVzdBoeLmVtaC52MS5VcGRhdGVDb25mbGljdFJlc3BvbnNlEk8KDkRlbGV0ZUNvbmZsaWN0Eh0uZW1oLnYxLkRlbGV0ZUNvbmZsaWN0UmVxdWVzdBoeLmVtaC52MS5EZWxldGVDb25mbGljdFJlc3BvbnNlQj1aO2NvZGViZXJnLm9yZy9UaHIwVFQxZS9lbWgvYmFja2VuZC9pbnRlcm5hbC9nZW4vZW1oL3YxO2VtaHYxYgZwcm90bzM", [file_emh_v1_enums_emh, file_emh_v1_common, file_emh_v1_conflict, file_buf_validate_validate]);

/**
 * CreateConflictRequest данные для создания нового конфликта. Даты в формате RFC3339.
 *
 * @generated from message emh.v1.CreateConflictRequest
 */
export type CreateConflictRequest = Message<"emh.v1.CreateConflictRequest"> & {
  /**
   * name - обязательное название конфликта.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * description - опциональное описание.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * type - обязательный тип конфликта.
   *
   * @generated from field: emh.v1.ConflictType type = 3;
   */
  type: ConflictType;

  /**
   * start_date - дата начала в формате RFC3339.
   *
   * @generated from field: string start_date = 4;
   */
  startDate: string;

  /**
   * end_date - дата окончания в формате RFC3339. Может быть пустой.
   *
   * @generated from field: string end_date = 5;
   */
  endDate: string;

  /**
   * parent_conflict_id - ID родительского конфликта.
   *
   * @generated from field: string parent_conflict_id = 6;
   */
  parentConflictId: string;

  /**
   * start_date_info - гибкая дата начала конфликта.
   * Если заполнено, имеет приоритет над start_date.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 7;
   */
  startDateInfo?: FlexibleDate | undefined;

  /**
   * end_date_info - гибкая дата окончания конфликта.
   * Если заполнено, имеет приоритет над end_date.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 8;
   */
  endDateInfo?: FlexibleDate | undefined;
};

/**
 * CreateConflictRequest данные для создания нового конфликта. Даты в формате RFC3339.
 *
 * @generated from message emh.v1.CreateConflictRequest
 */
export type CreateConflictRequestJson = {
  /**
   * name - обязательное название конфликта.
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * description - опциональное описание.
   *
   * @generated from field: string description = 2;
   */
  description?: string;

  /**
   * type - обязательный тип конфликта.
   *
   * @generated from field: emh.v1.ConflictType type = 3;
   */
  type?: ConflictTypeJson;

  /**
   * start_date - дата начала в формате RFC3339.
   *
   * @generated from field: string start_date = 4;
   */
  startDate?: string;

  /**
   * end_date - дата окончания в формате RFC3339. Может быть пустой.
   *
   * @generated from field: string end_date = 5;
   */
  endDate?: string;

  /**
   * parent_conflict_id - ID родительского конфликта.
   *
   * @generated from field: string parent_conflict_id = 6;
   */
  parentConflictId?: string;

  /**
   * start_date_info - гибкая дата начала конфликта.
   * Если заполнено, имеет приоритет над start_date.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 7;
   */
  startDateInfo?: FlexibleDateJson;

  /**
   * end_date_info - гибкая дата окончания конфликта.
   * Если заполнено, имеет приоритет над end_date.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 8;
   */
  endDateInfo?: FlexibleDateJson;
};

/**
 * Describes the message emh.v1.CreateConflictRequest.
 * Use `create(CreateConflictRequestSchema)` to create a new message.
 */
export const CreateConflictRequestSchema: GenMessage<CreateConflictRequest, {jsonType: CreateConflictRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 0);

/**
 * CreateConflictResponse результат успешного создания конфликта.
 *
 * @generated from message emh.v1.CreateConflictResponse
 */
export type CreateConflictResponse = Message<"emh.v1.CreateConflictResponse"> & {
  /**
   * id - UUID созданного конфликта.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * CreateConflictResponse результат успешного создания конфликта.
 *
 * @generated from message emh.v1.CreateConflictResponse
 */
export type CreateConflictResponseJson = {
  /**
   * id - UUID созданного конфликта.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.CreateConflictResponse.
 * Use `create(CreateConflictResponseSchema)` to create a new message.
 */
export const CreateConflictResponseSchema: GenMessage<CreateConflictResponse, {jsonType: CreateConflictResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 1);

/**
 * UpdateConflictRequest данные для частичного обновления конфликта.
 *
 * @generated from message emh.v1.UpdateConflictRequest
 */
export type UpdateConflictRequest = Message<"emh.v1.UpdateConflictRequest"> & {
  /**
   * id - UUID обновляемого конфликта (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - новое название.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description - новое описание.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * type - новый тип.
   *
   * @generated from field: emh.v1.ConflictType type = 4;
   */
  type: ConflictType;

  /**
   * start_date - новая дата начала.
   *
   * @generated from field: string start_date = 5;
   */
  startDate: string;

  /**
   * end_date - новая дата окончания.
   *
   * @generated from field: string end_date = 6;
   */
  endDate: string;

  /**
   * parent_conflict_id - новый родительский конфликт.
   *
   * @generated from field: string parent_conflict_id = 7;
   */
  parentConflictId: string;

  /**
   * field_mask - список полей для обновления.
   *
   * @generated from field: repeated string field_mask = 8;
   */
  fieldMask: string[];

  /**
   * start_date_info - новая гибкая дата начала.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 9;
   */
  startDateInfo?: FlexibleDate | undefined;

  /**
   * end_date_info - новая гибкая дата окончания.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 10;
   */
  endDateInfo?: FlexibleDate | undefined;
};

/**
 * UpdateConflictRequest данные для частичного обновления конфликта.
 *
 * @generated from message emh.v1.UpdateConflictRequest
 */
export type UpdateConflictRequestJson = {
  /**
   * id - UUID обновляемого конфликта (обязательно).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - новое название.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * description - новое описание.
   *
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * type - новый тип.
   *
   * @generated from field: emh.v1.ConflictType type = 4;
   */
  type?: ConflictTypeJson;

  /**
   * start_date - новая дата начала.
   *
   * @generated from field: string start_date = 5;
   */
  startDate?: string;

  /**
   * end_date - новая дата окончания.
   *
   * @generated from field: string end_date = 6;
   */
  endDate?: string;

  /**
   * parent_conflict_id - новый родительский конфликт.
   *
   * @generated from field: string parent_conflict_id = 7;
   */
  parentConflictId?: string;

  /**
   * field_mask - список полей для обновления.
   *
   * @generated from field: repeated string field_mask = 8;
   */
  fieldMask?: string[];

  /**
   * start_date_info - новая гибкая дата начала.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 9;
   */
  startDateInfo?: FlexibleDateJson;

  /**
   * end_date_info - новая гибкая дата окончания.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 10;
   */
  endDateInfo?: FlexibleDateJson;
};

/**
 * Describes the message emh.v1.UpdateConflictRequest.
 * Use `create(UpdateConflictRequestSchema)` to create a new message.
 */
export const UpdateConflictRequestSchema: GenMessage<UpdateConflictRequest, {jsonType: UpdateConflictRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 2);

/**
 * UpdateConflictResponse обновленный объект конфликта.
 *
 * @generated from message emh.v1.UpdateConflictResponse
 */
export type UpdateConflictResponse = Message<"emh.v1.UpdateConflictResponse"> & {
  /**
   * conflict - актуальное состояние конфликта после обновления.
   *
   * @generated from field: emh.v1.Conflict conflict = 1;
   */
  conflict?: Conflict | undefined;
};

/**
 * UpdateConflictResponse обновленный объект конфликта.
 *
 * @generated from message emh.v1.UpdateConflictResponse
 */
export type UpdateConflictResponseJson = {
  /**
   * conflict - актуальное состояние конфликта после обновления.
   *
   * @generated from field: emh.v1.Conflict conflict = 1;
   */
  conflict?: ConflictJson;
};

/**
 * Describes the message emh.v1.UpdateConflictResponse.
 * Use `create(UpdateConflictResponseSchema)` to create a new message.
 */
export const UpdateConflictResponseSchema: GenMessage<UpdateConflictResponse, {jsonType: UpdateConflictResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 3);

/**
 * DeleteConflictRequest запрос на удаление конфликта.
 *
 * @generated from message emh.v1.DeleteConflictRequest
 */
export type DeleteConflictRequest = Message<"emh.v1.DeleteConflictRequest"> & {
  /**
   * id - UUID удаляемого конфликта.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * DeleteConflictRequest запрос на удаление конфликта.
 *
 * @generated from message emh.v1.DeleteConflictRequest
 */
export type DeleteConflictRequestJson = {
  /**
   * id - UUID удаляемого конфликта.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.DeleteConflictRequest.
 * Use `create(DeleteConflictRequestSchema)` to create a new message.
 */
export const DeleteConflictRequestSchema: GenMessage<DeleteConflictRequest, {jsonType: DeleteConflictRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 4);

/**
 * DeleteConflictResponse подтверждение удаления.
 *
 * @generated from message emh.v1.DeleteConflictResponse
 */
export type DeleteConflictResponse = Message<"emh.v1.DeleteConflictResponse"> & {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * DeleteConflictResponse подтверждение удаления.
 *
 * @generated from message emh.v1.DeleteConflictResponse
 */
export type DeleteConflictResponseJson = {
  /**
   * success - true если удаление прошло успешно.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.DeleteConflictResponse.
 * Use `create(DeleteConflictResponseSchema)` to create a new message.
 */
export const DeleteConflictResponseSchema: GenMessage<DeleteConflictResponse, {jsonType: DeleteConflictResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict_admin, 5);

/**
 * ConflictAdminService защищенный сервис для управления справочником конфликтов.
 *
 * @generated from service emh.v1.ConflictAdminService
 */
export const ConflictAdminService: GenService<{
  /**
   * CreateConflict создает новую запись о конфликте.
   *
   * @generated from rpc emh.v1.ConflictAdminService.CreateConflict
   */
  createConflict: {
    methodKind: "unary";
    input: typeof CreateConflictRequestSchema;
    output: typeof CreateConflictResponseSchema;
  },
  /**
   * UpdateConflict частично обновляет существующий конфликт по field_mask.
   *
   * @generated from rpc emh.v1.ConflictAdminService.UpdateConflict
   */
  updateConflict: {
    methodKind: "unary";
    input: typeof UpdateConflictRequestSchema;
    output: typeof UpdateConflictResponseSchema;
  },
  /**
   * DeleteConflict удаляет конфликт. При наличии связанных героев вернет ошибку.
   *
   * @generated from rpc emh.v1.ConflictAdminService.DeleteConflict
   */
  deleteConflict: {
    methodKind: "unary";
    input: typeof DeleteConflictRequestSchema;
    output: typeof DeleteConflictResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_conflict_admin, 0);

