// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/conflict.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConflictType, ConflictTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { FlexibleDate, FlexibleDateJson, PaginationRequest, PaginationRequestJson, PaginationResponse, PaginationResponseJson } from "./common_pb";
import { file_emh_v1_common } from "./common_pb";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/conflict.proto.
 */
export const file_emh_v1_conflict: GenFile = /*@__PURE__*/
  fileDesc("ChVlbWgvdjEvY29uZmxpY3QucHJvdG8SBmVtaC52MSKzAgoIQ29uZmxpY3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIiCgR0eXBlGAQgASgOMhQuZW1oLnYxLkNvbmZsaWN0VHlwZRIuCgpzdGFydF9kYXRlGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCghlbmRfZGF0ZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASGgoScGFyZW50X2NvbmZsaWN0X2lkGAcgASgJEi0KD3N0YXJ0X2RhdGVfaW5mbxgIIAEoCzIULmVtaC52MS5GbGV4aWJsZURhdGUSKwoNZW5kX2RhdGVfaW5mbxgJIAEoCzIULmVtaC52MS5GbGV4aWJsZURhdGUiIAoSR2V0Q29uZmxpY3RSZXF1ZXN0EgoKAmlkGAEgASgJIjkKE0dldENvbmZsaWN0UmVzcG9uc2USIgoIY29uZmxpY3QYASABKAsyEC5lbWgudjEuQ29uZmxpY3QihQEKFExpc3RDb25mbGljdHNSZXF1ZXN0EiIKBHR5cGUYASABKA4yFC5lbWgudjEuQ29uZmxpY3RUeXBlEhoKEnBhcmVudF9jb25mbGljdF9pZBgCIAEoCRItCgpwYWdpbmF0aW9uGAMgASgLMhkuZW1oLnYxLlBhZ2luYXRpb25SZXF1ZXN0ImwKFUxpc3RDb25mbGljdHNSZXNwb25zZRIjCgljb25mbGljdHMYASADKAsyEC5lbWgudjEuQ29uZmxpY3QSLgoKcGFnaW5hdGlvbhgCIAEoCzIaLmVtaC52MS5QYWdpbmF0aW9uUmVzcG9uc2UypwEKD0NvbmZsaWN0U2VydmljZRJGCgtHZXRDb25mbGljdBIaLmVtaC52MS5HZXRDb25mbGljdFJlcXVlc3QaGy5lbWgudjEuR2V0Q29uZmxpY3RSZXNwb25zZRJMCg1MaXN0Q29uZmxpY3RzEhwuZW1oLnYxLkxpc3RDb25mbGljdHNSZXF1ZXN0Gh0uZW1oLnYxLkxpc3RDb25mbGljdHNSZXNwb25zZUI9Wjtjb2RlYmVyZy5vcmcvVGhyMFRUMWUvZW1oL2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2VtaC92MTtlbWh2MWIGcHJvdG8z", [file_emh_v1_enums_emh, file_emh_v1_common, file_google_protobuf_timestamp]);

/**
 * Conflict представляет военный конфликт или отдельную операцию.
 *
 * @generated from message emh.v1.Conflict
 */
export type Conflict = Message<"emh.v1.Conflict"> & {
  /**
   * id - уникальный идентификатор конфликта (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - официальное название конфликта (например, "Великая Отечественная война").
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description - краткое историческое описание конфликта.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * type - категория конфликта для фильтрации.
   *
   * @generated from field: emh.v1.ConflictType type = 4;
   */
  type: ConflictType;

  /**
   * start_date - дата начала конфликта.
   *
   * @generated from field: google.protobuf.Timestamp start_date = 5;
   */
  startDate?: Timestamp | undefined;

  /**
   * end_date - дата окончания конфликта. Может быть пустой для текущих конфликтов.
   *
   * @generated from field: google.protobuf.Timestamp end_date = 6;
   */
  endDate?: Timestamp | undefined;

  /**
   * parent_conflict_id - ID родительского конфликта для иерархии (например, битва внутри войны).
   *
   * @generated from field: string parent_conflict_id = 7;
   */
  parentConflictId: string;

  /**
   * start_date_info - гибкая дата начала конфликта.
   * Если заполнено, имеет приоритет над start_date.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 8;
   */
  startDateInfo?: FlexibleDate | undefined;

  /**
   * end_date_info - гибкая дата окончания конфликта.
   * Если заполнено, имеет приоритет над end_date.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 9;
   */
  endDateInfo?: FlexibleDate | undefined;
};

/**
 * Conflict представляет военный конфликт или отдельную операцию.
 *
 * @generated from message emh.v1.Conflict
 */
export type ConflictJson = {
  /**
   * id - уникальный идентификатор конфликта (UUID).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - официальное название конфликта (например, "Великая Отечественная война").
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * description - краткое историческое описание конфликта.
   *
   * @generated from field: string description = 3;
   */
  description?: string;

  /**
   * type - категория конфликта для фильтрации.
   *
   * @generated from field: emh.v1.ConflictType type = 4;
   */
  type?: ConflictTypeJson;

  /**
   * start_date - дата начала конфликта.
   *
   * @generated from field: google.protobuf.Timestamp start_date = 5;
   */
  startDate?: TimestampJson;

  /**
   * end_date - дата окончания конфликта. Может быть пустой для текущих конфликтов.
   *
   * @generated from field: google.protobuf.Timestamp end_date = 6;
   */
  endDate?: TimestampJson;

  /**
   * parent_conflict_id - ID родительского конфликта для иерархии (например, битва внутри войны).
   *
   * @generated from field: string parent_conflict_id = 7;
   */
  parentConflictId?: string;

  /**
   * start_date_info - гибкая дата начала конфликта.
   * Если заполнено, имеет приоритет над start_date.
   *
   * @generated from field: emh.v1.FlexibleDate start_date_info = 8;
   */
  startDateInfo?: FlexibleDateJson;

  /**
   * end_date_info - гибкая дата окончания конфликта.
   * Если заполнено, имеет приоритет над end_date.
   *
   * @generated from field: emh.v1.FlexibleDate end_date_info = 9;
   */
  endDateInfo?: FlexibleDateJson;
};

/**
 * Describes the message emh.v1.Conflict.
 * Use `create(ConflictSchema)` to create a new message.
 */
export const ConflictSchema: GenMessage<Conflict, {jsonType: ConflictJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict, 0);

/**
 * GetConflictRequest запрос на получение детальной информации о конфликте.
 *
 * @generated from message emh.v1.GetConflictRequest
 */
export type GetConflictRequest = Message<"emh.v1.GetConflictRequest"> & {
  /**
   * id - UUID конфликта.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * GetConflictRequest запрос на получение детальной информации о конфликте.
 *
 * @generated from message emh.v1.GetConflictRequest
 */
export type GetConflictRequestJson = {
  /**
   * id - UUID конфликта.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.GetConflictRequest.
 * Use `create(GetConflictRequestSchema)` to create a new message.
 */
export const GetConflictRequestSchema: GenMessage<GetConflictRequest, {jsonType: GetConflictRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict, 1);

/**
 * GetConflictResponse содержит полную информацию о запрошенном конфликте.
 *
 * @generated from message emh.v1.GetConflictResponse
 */
export type GetConflictResponse = Message<"emh.v1.GetConflictResponse"> & {
  /**
   * conflict - объект конфликта.
   *
   * @generated from field: emh.v1.Conflict conflict = 1;
   */
  conflict?: Conflict | undefined;
};

/**
 * GetConflictResponse содержит полную информацию о запрошенном конфликте.
 *
 * @generated from message emh.v1.GetConflictResponse
 */
export type GetConflictResponseJson = {
  /**
   * conflict - объект конфликта.
   *
   * @generated from field: emh.v1.Conflict conflict = 1;
   */
  conflict?: ConflictJson;
};

/**
 * Describes the message emh.v1.GetConflictResponse.
 * Use `create(GetConflictResponseSchema)` to create a new message.
 */
export const GetConflictResponseSchema: GenMessage<GetConflictResponse, {jsonType: GetConflictResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict, 2);

/**
 * ListConflictsRequest параметры фильтрации и выборки списка конфликтов.
 *
 * @generated from message emh.v1.ListConflictsRequest
 */
export type ListConflictsRequest = Message<"emh.v1.ListConflictsRequest"> & {
  /**
   * type - фильтр по типу конфликта. UNSPECIFIED возвращает все типы.
   *
   * @generated from field: emh.v1.ConflictType type = 1;
   */
  type: ConflictType;

  /**
   * parent_conflict_id - фильтр по родительскому конфликту для получения подчиненных операций.
   *
   * @generated from field: string parent_conflict_id = 2;
   */
  parentConflictId: string;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 3;
   */
  pagination?: PaginationRequest | undefined;
};

/**
 * ListConflictsRequest параметры фильтрации и выборки списка конфликтов.
 *
 * @generated from message emh.v1.ListConflictsRequest
 */
export type ListConflictsRequestJson = {
  /**
   * type - фильтр по типу конфликта. UNSPECIFIED возвращает все типы.
   *
   * @generated from field: emh.v1.ConflictType type = 1;
   */
  type?: ConflictTypeJson;

  /**
   * parent_conflict_id - фильтр по родительскому конфликту для получения подчиненных операций.
   *
   * @generated from field: string parent_conflict_id = 2;
   */
  parentConflictId?: string;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 3;
   */
  pagination?: PaginationRequestJson;
};

/**
 * Describes the message emh.v1.ListConflictsRequest.
 * Use `create(ListConflictsRequestSchema)` to create a new message.
 */
export const ListConflictsRequestSchema: GenMessage<ListConflictsRequest, {jsonType: ListConflictsRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict, 3);

/**
 * ListConflictsResponse список конфликтов без пагинации (справочник обычно небольшой).
 *
 * @generated from message emh.v1.ListConflictsResponse
 */
export type ListConflictsResponse = Message<"emh.v1.ListConflictsResponse"> & {
  /**
   * conflicts - массив объектов конфликтов.
   *
   * @generated from field: repeated emh.v1.Conflict conflicts = 1;
   */
  conflicts: Conflict[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse | undefined;
};

/**
 * ListConflictsResponse список конфликтов без пагинации (справочник обычно небольшой).
 *
 * @generated from message emh.v1.ListConflictsResponse
 */
export type ListConflictsResponseJson = {
  /**
   * conflicts - массив объектов конфликтов.
   *
   * @generated from field: repeated emh.v1.Conflict conflicts = 1;
   */
  conflicts?: ConflictJson[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponseJson;
};

/**
 * Describes the message emh.v1.ListConflictsResponse.
 * Use `create(ListConflictsResponseSchema)` to create a new message.
 */
export const ListConflictsResponseSchema: GenMessage<ListConflictsResponse, {jsonType: ListConflictsResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_conflict, 4);

/**
 * ConflictService публичный сервис для чтения справочника конфликтов.
 *
 * @generated from service emh.v1.ConflictService
 */
export const ConflictService: GenService<{
  /**
   * GetConflict возвращает детальную информацию о конкретном конфликте по ID.
   *
   * @generated from rpc emh.v1.ConflictService.GetConflict
   */
  getConflict: {
    methodKind: "unary";
    input: typeof GetConflictRequestSchema;
    output: typeof GetConflictResponseSchema;
  },
  /**
   * ListConflicts возвращает отфильтрованный список всех конфликтов.
   *
   * @generated from rpc emh.v1.ConflictService.ListConflicts
   */
  listConflicts: {
    methodKind: "unary";
    input: typeof ListConflictsRequestSchema;
    output: typeof ListConflictsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_conflict, 0);

