// Сервис обратной связи: приём сообщений с формы /contacts и отправка email через SMTP.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/contact.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/contact.proto.
 */
export const file_emh_v1_contact: GenFile = /*@__PURE__*/
  fileDesc("ChRlbWgvdjEvY29udGFjdC5wcm90bxIGZW1oLnYxItwBChtDcmVhdGVDb250YWN0TWVzc2FnZVJlcXVlc3QSGAoEbmFtZRgBIAEoCUIKukgHcgUQAhjIARIZCgVlbWFpbBgCIAEoCUIKukgHcgVgARj+ARIZCgdzdWJqZWN0GAMgASgJQgi6SAVyAxjIARIbCgdtZXNzYWdlGAQgASgJQgq6SAdyBRAKGIgnEhoKCHBhZ2VfdXJsGAUgASgJQgi6SAVyAxiAEBIaCghob25leXBvdBgGIAEoCUIIukgFcgMYyAESGAoHY29uc2VudBgHIAEoCEIHukgEagIIASI0ChxDcmVhdGVDb250YWN0TWVzc2FnZVJlc3BvbnNlEhQKAmlkGAEgASgJQgi6SAVyA7ABATJzCg5Db250YWN0U2VydmljZRJhChRDcmVhdGVDb250YWN0TWVzc2FnZRIjLmVtaC52MS5DcmVhdGVDb250YWN0TWVzc2FnZVJlcXVlc3QaJC5lbWgudjEuQ3JlYXRlQ29udGFjdE1lc3NhZ2VSZXNwb25zZUI9Wjtjb2RlYmVyZy5vcmcvVGhyMFRUMWUvZW1oL2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2VtaC92MTtlbWh2MWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * CreateContactMessageRequest — запрос на создание сообщения обратной связи.
 * Форма НЕ предназначена для отправки данных о героях (для этого есть SubmissionService).
 *
 * @generated from message emh.v1.CreateContactMessageRequest
 */
export type CreateContactMessageRequest = Message<"emh.v1.CreateContactMessageRequest"> & {
  /**
   * name — имя отправителя (обязательно, 2–200 символов).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * email — email отправителя для ответа.
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * subject — тема обращения (опционально, до 200 символов).
   *
   * @generated from field: string subject = 3;
   */
  subject: string;

  /**
   * message — текст сообщения (обязательно, 10–5000 символов).
   *
   * @generated from field: string message = 4;
   */
  message: string;

  /**
   * page_url — страница, с которой была отправлена форма (для контекста).
   *
   * @generated from field: string page_url = 5;
   */
  pageUrl: string;

  /**
   * honeypot — скрытое поле для простых ботов. Должно быть пустым.
   * Если заполнено — запрос принимается, но email не отправляется.
   *
   * @generated from field: string honeypot = 6;
   */
  honeypot: string;

  /**
   * consent — согласие на обработку персональных данных. Обязательно true.
   *
   * @generated from field: bool consent = 7;
   */
  consent: boolean;
};

/**
 * CreateContactMessageRequest — запрос на создание сообщения обратной связи.
 * Форма НЕ предназначена для отправки данных о героях (для этого есть SubmissionService).
 *
 * @generated from message emh.v1.CreateContactMessageRequest
 */
export type CreateContactMessageRequestJson = {
  /**
   * name — имя отправителя (обязательно, 2–200 символов).
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * email — email отправителя для ответа.
   *
   * @generated from field: string email = 2;
   */
  email?: string;

  /**
   * subject — тема обращения (опционально, до 200 символов).
   *
   * @generated from field: string subject = 3;
   */
  subject?: string;

  /**
   * message — текст сообщения (обязательно, 10–5000 символов).
   *
   * @generated from field: string message = 4;
   */
  message?: string;

  /**
   * page_url — страница, с которой была отправлена форма (для контекста).
   *
   * @generated from field: string page_url = 5;
   */
  pageUrl?: string;

  /**
   * honeypot — скрытое поле для простых ботов. Должно быть пустым.
   * Если заполнено — запрос принимается, но email не отправляется.
   *
   * @generated from field: string honeypot = 6;
   */
  honeypot?: string;

  /**
   * consent — согласие на обработку персональных данных. Обязательно true.
   *
   * @generated from field: bool consent = 7;
   */
  consent?: boolean;
};

/**
 * Describes the message emh.v1.CreateContactMessageRequest.
 * Use `create(CreateContactMessageRequestSchema)` to create a new message.
 */
export const CreateContactMessageRequestSchema: GenMessage<CreateContactMessageRequest, {jsonType: CreateContactMessageRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_contact, 0);

/**
 * CreateContactMessageResponse — результат создания сообщения.
 *
 * @generated from message emh.v1.CreateContactMessageResponse
 */
export type CreateContactMessageResponse = Message<"emh.v1.CreateContactMessageResponse"> & {
  /**
   * id — UUID созданного сообщения в таблице contact_messages.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * CreateContactMessageResponse — результат создания сообщения.
 *
 * @generated from message emh.v1.CreateContactMessageResponse
 */
export type CreateContactMessageResponseJson = {
  /**
   * id — UUID созданного сообщения в таблице contact_messages.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.CreateContactMessageResponse.
 * Use `create(CreateContactMessageResponseSchema)` to create a new message.
 */
export const CreateContactMessageResponseSchema: GenMessage<CreateContactMessageResponse, {jsonType: CreateContactMessageResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_contact, 1);

/**
 * ContactService — публичный сервис обратной связи.
 * Endpoint: POST /emh.v1.ContactService/CreateContactMessage
 *
 * @generated from service emh.v1.ContactService
 */
export const ContactService: GenService<{
  /**
   * CreateContactMessage принимает сообщение формы обратной связи,
   * сохраняет его в БД и (если SMTP включён и это не honeypot)
   * инициирует отправку письма владельцу проекта.
   *
   * @generated from rpc emh.v1.ContactService.CreateContactMessage
   */
  createContactMessage: {
    methodKind: "unary";
    input: typeof CreateContactMessageRequestSchema;
    output: typeof CreateContactMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_contact, 0);

