// Выносим перечисления в отдельный файл для переиспользования и чистоты контрактов.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/enums_emh.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file emh/v1/enums_emh.proto.
 */
export const file_emh_v1_enums_emh: GenFile = /*@__PURE__*/
  fileDesc("ChZlbWgvdjEvZW51bXNfZW1oLnByb3RvEgZlbWgudjEqmAEKEVB1YmxpY2F0aW9uU3RhdHVzEiIKHlBVQkxJQ0FUSU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEhwKGFBVQkxJQ0FUSU9OX1NUQVRVU19EUkFGVBABEiAKHFBVQkxJQ0FUSU9OX1NUQVRVU19QVUJMSVNIRUQQAhIfChtQVUJMSUNBVElPTl9TVEFUVVNfQVJDSElWRUQQAyqxAQoMTG9jYXRpb25UeXBlEh0KGUxPQ0FUSU9OX1RZUEVfVU5TUEVDSUZJRUQQABIZChVMT0NBVElPTl9UWVBFX0NPVU5UUlkQARIYChRMT0NBVElPTl9UWVBFX1JFR0lPThACEhYKEkxPQ0FUSU9OX1RZUEVfQ0lUWRADEhkKFUxPQ0FUSU9OX1RZUEVfVklMTEFHRRAEEhoKFkxPQ0FUSU9OX1RZUEVfQ0VNRVRFUlkQBSqzAQoQSGVyb0xvY2F0aW9uVHlwZRIiCh5IRVJPX0xPQ0FUSU9OX1RZUEVfVU5TUEVDSUZJRUQQABIcChhIRVJPX0xPQ0FUSU9OX1RZUEVfQklSVEgQARIcChhIRVJPX0xPQ0FUSU9OX1RZUEVfREVBVEgQAhIdChlIRVJPX0xPQ0FUSU9OX1RZUEVfQlVSSUFMEAMSIAocSEVST19MT0NBVElPTl9UWVBFX1JFU0lERU5DRRAEKsoBCgxDb25mbGljdFR5cGUSHQoZQ09ORkxJQ1RfVFlQRV9VTlNQRUNJRklFRBAAEhgKFENPTkZMSUNUX1RZUEVfR0xPQkFMEAESFwoTQ09ORkxJQ1RfVFlQRV9MT0NBTBACEh4KGkNPTkZMSUNUX1RZUEVfUEVBQ0VLRUVQSU5HEAMSIwofQ09ORkxJQ1RfVFlQRV9DT1VOVEVSX1RFUlJPUklTTRAEEiMKH0NPTkZMSUNUX1RZUEVfU1BFQ0lBTF9PUEVSQVRJT04QBSrrAQoNRGF0ZVByZWNpc2lvbhIeChpEQVRFX1BSRUNJU0lPTl9VTlNQRUNJRklFRBAAEhgKFERBVEVfUFJFQ0lTSU9OX0VYQUNUEAESGAoUREFURV9QUkVDSVNJT05fTU9OVEgQAhIXChNEQVRFX1BSRUNJU0lPTl9ZRUFSEAMSGQoVREFURV9QUkVDSVNJT05fU0VBU09OEAQSHAoYREFURV9QUkVDSVNJT05fREFZX01PTlRIEAUSGAoUREFURV9QUkVDSVNJT05fUkFOR0UQBhIaChZEQVRFX1BSRUNJU0lPTl9VTktOT1dOEAdCPVo7Y29kZWJlcmcub3JnL1RocjBUVDFlL2VtaC9iYWNrZW5kL2ludGVybmFsL2dlbi9lbWgvdjE7ZW1odjFiBnByb3RvMw");

/**
 * PublicationStatus определяет видимость записи на сайте и в админке.
 *
 * @generated from enum emh.v1.PublicationStatus
 */
export enum PublicationStatus {
  /**
   * PUBLICATION_STATUS_UNSPECIFIED - статус не задан (ошибка валидации).
   *
   * @generated from enum value: PUBLICATION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * PUBLICATION_STATUS_DRAFT - черновик или запись на модерации.
   *
   * @generated from enum value: PUBLICATION_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * PUBLICATION_STATUS_PUBLISHED - запись опубликована и доступна всем.
   *
   * @generated from enum value: PUBLICATION_STATUS_PUBLISHED = 2;
   */
  PUBLISHED = 2,

  /**
   * PUBLICATION_STATUS_ARCHIVED - запись скрыта с сайта, но сохранена в БД.
   *
   * @generated from enum value: PUBLICATION_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * PublicationStatus определяет видимость записи на сайте и в админке.
 *
 * @generated from enum emh.v1.PublicationStatus
 */
export type PublicationStatusJson = "PUBLICATION_STATUS_UNSPECIFIED" | "PUBLICATION_STATUS_DRAFT" | "PUBLICATION_STATUS_PUBLISHED" | "PUBLICATION_STATUS_ARCHIVED";

/**
 * Describes the enum emh.v1.PublicationStatus.
 */
export const PublicationStatusSchema: GenEnum<PublicationStatus, PublicationStatusJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_enums_emh, 0);

/**
 * LocationType классифицирует географические объекты.
 *
 * @generated from enum emh.v1.LocationType
 */
export enum LocationType {
  /**
   * LOCATION_TYPE_UNSPECIFIED - тип не задан.
   *
   * @generated from enum value: LOCATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * LOCATION_TYPE_COUNTRY - страна.
   *
   * @generated from enum value: LOCATION_TYPE_COUNTRY = 1;
   */
  COUNTRY = 1,

  /**
   * LOCATION_TYPE_REGION - область, край, республика.
   *
   * @generated from enum value: LOCATION_TYPE_REGION = 2;
   */
  REGION = 2,

  /**
   * LOCATION_TYPE_CITY - город.
   *
   * @generated from enum value: LOCATION_TYPE_CITY = 3;
   */
  CITY = 3,

  /**
   * LOCATION_TYPE_VILLAGE - село, деревня, поселок.
   *
   * @generated from enum value: LOCATION_TYPE_VILLAGE = 4;
   */
  VILLAGE = 4,

  /**
   * LOCATION_TYPE_CEMETERY - кладбище или мемориальный комплекс.
   *
   * @generated from enum value: LOCATION_TYPE_CEMETERY = 5;
   */
  CEMETERY = 5,
}

/**
 * LocationType классифицирует географические объекты.
 *
 * @generated from enum emh.v1.LocationType
 */
export type LocationTypeJson = "LOCATION_TYPE_UNSPECIFIED" | "LOCATION_TYPE_COUNTRY" | "LOCATION_TYPE_REGION" | "LOCATION_TYPE_CITY" | "LOCATION_TYPE_VILLAGE" | "LOCATION_TYPE_CEMETERY";

/**
 * Describes the enum emh.v1.LocationType.
 */
export const LocationTypeSchema: GenEnum<LocationType, LocationTypeJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_enums_emh, 1);

/**
 * HeroLocationType определяет роль локации в биографии героя.
 *
 * @generated from enum emh.v1.HeroLocationType
 */
export enum HeroLocationType {
  /**
   * HERO_LOCATION_TYPE_UNSPECIFIED - тип связи не задан.
   *
   * @generated from enum value: HERO_LOCATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * HERO_LOCATION_TYPE_BIRTH - место рождения.
   *
   * @generated from enum value: HERO_LOCATION_TYPE_BIRTH = 1;
   */
  BIRTH = 1,

  /**
   * HERO_LOCATION_TYPE_DEATH - место гибели.
   *
   * @generated from enum value: HERO_LOCATION_TYPE_DEATH = 2;
   */
  DEATH = 2,

  /**
   * HERO_LOCATION_TYPE_BURIAL - место захоронения.
   *
   * @generated from enum value: HERO_LOCATION_TYPE_BURIAL = 3;
   */
  BURIAL = 3,

  /**
   * HERO_LOCATION_TYPE_RESIDENCE - место проживания до конфликта.
   *
   * @generated from enum value: HERO_LOCATION_TYPE_RESIDENCE = 4;
   */
  RESIDENCE = 4,
}

/**
 * HeroLocationType определяет роль локации в биографии героя.
 *
 * @generated from enum emh.v1.HeroLocationType
 */
export type HeroLocationTypeJson = "HERO_LOCATION_TYPE_UNSPECIFIED" | "HERO_LOCATION_TYPE_BIRTH" | "HERO_LOCATION_TYPE_DEATH" | "HERO_LOCATION_TYPE_BURIAL" | "HERO_LOCATION_TYPE_RESIDENCE";

/**
 * Describes the enum emh.v1.HeroLocationType.
 */
export const HeroLocationTypeSchema: GenEnum<HeroLocationType, HeroLocationTypeJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_enums_emh, 2);

/**
 * ConflictType классифицирует военные конфликты.
 *
 * @generated from enum emh.v1.ConflictType
 */
export enum ConflictType {
  /**
   * CONFLICT_TYPE_UNSPECIFIED - тип конфликта не задан.
   *
   * @generated from enum value: CONFLICT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * CONFLICT_TYPE_GLOBAL - мировые войны.
   *
   * @generated from enum value: CONFLICT_TYPE_GLOBAL = 1;
   */
  GLOBAL = 1,

  /**
   * CONFLICT_TYPE_LOCAL - локальные военные конфликты.
   *
   * @generated from enum value: CONFLICT_TYPE_LOCAL = 2;
   */
  LOCAL = 2,

  /**
   * CONFLICT_TYPE_PEACEKEEPING - миротворческие операции.
   *
   * @generated from enum value: CONFLICT_TYPE_PEACEKEEPING = 3;
   */
  PEACEKEEPING = 3,

  /**
   * CONFLICT_TYPE_COUNTER_TERRORISM - контртеррористические операции (КТО).
   *
   * @generated from enum value: CONFLICT_TYPE_COUNTER_TERRORISM = 4;
   */
  COUNTER_TERRORISM = 4,

  /**
   * CONFLICT_TYPE_SPECIAL_OPERATION - специальная военная операция (СВО) и подобные.
   *
   * @generated from enum value: CONFLICT_TYPE_SPECIAL_OPERATION = 5;
   */
  SPECIAL_OPERATION = 5,
}

/**
 * ConflictType классифицирует военные конфликты.
 *
 * @generated from enum emh.v1.ConflictType
 */
export type ConflictTypeJson = "CONFLICT_TYPE_UNSPECIFIED" | "CONFLICT_TYPE_GLOBAL" | "CONFLICT_TYPE_LOCAL" | "CONFLICT_TYPE_PEACEKEEPING" | "CONFLICT_TYPE_COUNTER_TERRORISM" | "CONFLICT_TYPE_SPECIAL_OPERATION";

/**
 * Describes the enum emh.v1.ConflictType.
 */
export const ConflictTypeSchema: GenEnum<ConflictType, ConflictTypeJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_enums_emh, 3);

/**
 * DatePrecision определяет уровень точности гибкой даты.
 *
 * @generated from enum emh.v1.DatePrecision
 */
export enum DatePrecision {
  /**
   * DATE_PRECISION_UNSPECIFIED означает, что точность даты не указана.
   *
   * @generated from enum value: DATE_PRECISION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * DATE_PRECISION_EXACT означает точную дату формата YYYY-MM-DD.
   *
   * @generated from enum value: DATE_PRECISION_EXACT = 1;
   */
  EXACT = 1,

  /**
   * DATE_PRECISION_MONTH означает, что известны только год и месяц.
   *
   * @generated from enum value: DATE_PRECISION_MONTH = 2;
   */
  MONTH = 2,

  /**
   * DATE_PRECISION_YEAR означает, что известен только год.
   *
   * @generated from enum value: DATE_PRECISION_YEAR = 3;
   */
  YEAR = 3,

  /**
   * DATE_PRECISION_SEASON означает сезон и год, например "Лето 1989".
   *
   * @generated from enum value: DATE_PRECISION_SEASON = 4;
   */
  SEASON = 4,

  /**
   * DATE_PRECISION_DAY_MONTH означает день и месяц без года, например "28 июля".
   *
   * @generated from enum value: DATE_PRECISION_DAY_MONTH = 5;
   */
  DAY_MONTH = 5,

  /**
   * DATE_PRECISION_RANGE зарезервировано для диапазона дат, например "1994-1995".
   *
   * @generated from enum value: DATE_PRECISION_RANGE = 6;
   */
  RANGE = 6,

  /**
   * DATE_PRECISION_UNKNOWN означает, что дата неизвестна и есть только текстовое описание.
   *
   * @generated from enum value: DATE_PRECISION_UNKNOWN = 7;
   */
  UNKNOWN = 7,
}

/**
 * DatePrecision определяет уровень точности гибкой даты.
 *
 * @generated from enum emh.v1.DatePrecision
 */
export type DatePrecisionJson = "DATE_PRECISION_UNSPECIFIED" | "DATE_PRECISION_EXACT" | "DATE_PRECISION_MONTH" | "DATE_PRECISION_YEAR" | "DATE_PRECISION_SEASON" | "DATE_PRECISION_DAY_MONTH" | "DATE_PRECISION_RANGE" | "DATE_PRECISION_UNKNOWN";

/**
 * Describes the enum emh.v1.DatePrecision.
 */
export const DatePrecisionSchema: GenEnum<DatePrecision, DatePrecisionJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_enums_emh, 4);

