// Административный сервис управления LLM-провайдерами.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/llm_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/llm_admin.proto.
 */
export const file_emh_v1_llm_admin: GenFile = /*@__PURE__*/
  fileDesc("ChZlbWgvdjEvbGxtX2FkbWluLnByb3RvEgZlbWgudjEi3AEKD0xsbVByb3ZpZGVySW5mbxIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHR5cGUYAyABKAkSDQoFbW9kZWwYBCABKAkSEQoJaXNfYWN0aXZlGAUgASgIEhAKCHByaW9yaXR5GAYgASgFEg0KBW5vdGVzGAcgASgJEi4KCmNyZWF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIhkKF0xpc3RMbG1Qcm92aWRlcnNSZXF1ZXN0IlUKGExpc3RMbG1Qcm92aWRlcnNSZXNwb25zZRIqCglwcm92aWRlcnMYASADKAsyFy5lbWgudjEuTGxtUHJvdmlkZXJJbmZvEg0KBWNvdW50GAIgASgFIjMKG1NldEFjdGl2ZUxsbVByb3ZpZGVyUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOwAQEiWgocU2V0QWN0aXZlTGxtUHJvdmlkZXJSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEikKCHByb3ZpZGVyGAIgASgLMhcuZW1oLnYxLkxsbVByb3ZpZGVySW5mbyJMChZUZXN0TGxtUHJvdmlkZXJSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA7ABARIcCgt0ZXN0X3Byb21wdBgCIAEoCUIHukgEcgIQASJzChdUZXN0TGxtUHJvdmlkZXJSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEhQKDHJhd19yZXNwb25zZRgCIAEoCRIaChJwcm9jZXNzaW5nX3RpbWVfbXMYAyABKAMSFQoNZXJyb3JfbWVzc2FnZRgEIAEoCSJ1ChhVcGRhdGVMbG1Qcm92aWRlclJlcXVlc3QSFAoCaWQYASABKAlCCLpIBXIDsAEBEhgKCHByaW9yaXR5GAIgASgFQga6SAPYAQESFQoFbm90ZXMYAyABKAlCBrpIA9gBARISCgpmaWVsZF9tYXNrGAQgAygJIkYKGVVwZGF0ZUxsbVByb3ZpZGVyUmVzcG9uc2USKQoIcHJvdmlkZXIYASABKAsyFy5lbWgudjEuTGxtUHJvdmlkZXJJbmZvMvkCCg9MbG1BZG1pblNlcnZpY2USVQoQTGlzdExsbVByb3ZpZGVycxIfLmVtaC52MS5MaXN0TGxtUHJvdmlkZXJzUmVxdWVzdBogLmVtaC52MS5MaXN0TGxtUHJvdmlkZXJzUmVzcG9uc2USYQoUU2V0QWN0aXZlTGxtUHJvdmlkZXISIy5lbWgudjEuU2V0QWN0aXZlTGxtUHJvdmlkZXJSZXF1ZXN0GiQuZW1oLnYxLlNldEFjdGl2ZUxsbVByb3ZpZGVyUmVzcG9uc2USUgoPVGVzdExsbVByb3ZpZGVyEh4uZW1oLnYxLlRlc3RMbG1Qcm92aWRlclJlcXVlc3QaHy5lbWgudjEuVGVzdExsbVByb3ZpZGVyUmVzcG9uc2USWAoRVXBkYXRlTGxtUHJvdmlkZXISIC5lbWgudjEuVXBkYXRlTGxtUHJvdmlkZXJSZXF1ZXN0GiEuZW1oLnYxLlVwZGF0ZUxsbVByb3ZpZGVyUmVzcG9uc2VCPVo7Y29kZWJlcmcub3JnL1RocjBUVDFlL2VtaC9iYWNrZW5kL2ludGVybmFsL2dlbi9lbWgvdjE7ZW1odjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_buf_validate_validate]);

/**
 * LlmProviderInfo информация о провайдере для админки.
 *
 * @generated from message emh.v1.LlmProviderInfo
 */
export type LlmProviderInfo = Message<"emh.v1.LlmProviderInfo"> & {
  /**
   * id - уникальный идентификатор записи провайдера в БД (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - уникальное имя провайдера (совпадает с конфигом).
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * type - тип провайдера (ollama, openai_compatible, anthropic).
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * model - название используемой модели.
   *
   * @generated from field: string model = 4;
   */
  model: string;

  /**
   * is_active - является ли провайдер текущим активным.
   *
   * @generated from field: bool is_active = 5;
   */
  isActive: boolean;

  /**
   * priority - приоритет провайдера (для fallback-логики).
   *
   * @generated from field: int32 priority = 6;
   */
  priority: number;

  /**
   * notes - заметки администратора.
   *
   * @generated from field: string notes = 7;
   */
  notes: string;

  /**
   * created_at - дата и время создания записи.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp | undefined;

  /**
   * updated_at - дата и время последнего обновления.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * LlmProviderInfo информация о провайдере для админки.
 *
 * @generated from message emh.v1.LlmProviderInfo
 */
export type LlmProviderInfoJson = {
  /**
   * id - уникальный идентификатор записи провайдера в БД (UUID).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - уникальное имя провайдера (совпадает с конфигом).
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * type - тип провайдера (ollama, openai_compatible, anthropic).
   *
   * @generated from field: string type = 3;
   */
  type?: string;

  /**
   * model - название используемой модели.
   *
   * @generated from field: string model = 4;
   */
  model?: string;

  /**
   * is_active - является ли провайдер текущим активным.
   *
   * @generated from field: bool is_active = 5;
   */
  isActive?: boolean;

  /**
   * priority - приоритет провайдера (для fallback-логики).
   *
   * @generated from field: int32 priority = 6;
   */
  priority?: number;

  /**
   * notes - заметки администратора.
   *
   * @generated from field: string notes = 7;
   */
  notes?: string;

  /**
   * created_at - дата и время создания записи.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: TimestampJson;

  /**
   * updated_at - дата и время последнего обновления.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: TimestampJson;
};

/**
 * Describes the message emh.v1.LlmProviderInfo.
 * Use `create(LlmProviderInfoSchema)` to create a new message.
 */
export const LlmProviderInfoSchema: GenMessage<LlmProviderInfo, {jsonType: LlmProviderInfoJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 0);

/**
 * ListLlmProvidersRequest запрос списка провайдеров.
 *
 * @generated from message emh.v1.ListLlmProvidersRequest
 */
export type ListLlmProvidersRequest = Message<"emh.v1.ListLlmProvidersRequest"> & {
};

/**
 * ListLlmProvidersRequest запрос списка провайдеров.
 *
 * @generated from message emh.v1.ListLlmProvidersRequest
 */
export type ListLlmProvidersRequestJson = {
};

/**
 * Describes the message emh.v1.ListLlmProvidersRequest.
 * Use `create(ListLlmProvidersRequestSchema)` to create a new message.
 */
export const ListLlmProvidersRequestSchema: GenMessage<ListLlmProvidersRequest, {jsonType: ListLlmProvidersRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 1);

/**
 * ListLlmProvidersResponse список провайдеров.
 *
 * @generated from message emh.v1.ListLlmProvidersResponse
 */
export type ListLlmProvidersResponse = Message<"emh.v1.ListLlmProvidersResponse"> & {
  /**
   * providers - массив настроенных провайдеров.
   *
   * @generated from field: repeated emh.v1.LlmProviderInfo providers = 1;
   */
  providers: LlmProviderInfo[];

  /**
   * count - общее количество провайдеров в системе.
   *
   * @generated from field: int32 count = 2;
   */
  count: number;
};

/**
 * ListLlmProvidersResponse список провайдеров.
 *
 * @generated from message emh.v1.ListLlmProvidersResponse
 */
export type ListLlmProvidersResponseJson = {
  /**
   * providers - массив настроенных провайдеров.
   *
   * @generated from field: repeated emh.v1.LlmProviderInfo providers = 1;
   */
  providers?: LlmProviderInfoJson[];

  /**
   * count - общее количество провайдеров в системе.
   *
   * @generated from field: int32 count = 2;
   */
  count?: number;
};

/**
 * Describes the message emh.v1.ListLlmProvidersResponse.
 * Use `create(ListLlmProvidersResponseSchema)` to create a new message.
 */
export const ListLlmProvidersResponseSchema: GenMessage<ListLlmProvidersResponse, {jsonType: ListLlmProvidersResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 2);

/**
 * SetActiveLlmProviderRequest запрос на активацию провайдера.
 *
 * @generated from message emh.v1.SetActiveLlmProviderRequest
 */
export type SetActiveLlmProviderRequest = Message<"emh.v1.SetActiveLlmProviderRequest"> & {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * SetActiveLlmProviderRequest запрос на активацию провайдера.
 *
 * @generated from message emh.v1.SetActiveLlmProviderRequest
 */
export type SetActiveLlmProviderRequestJson = {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.SetActiveLlmProviderRequest.
 * Use `create(SetActiveLlmProviderRequestSchema)` to create a new message.
 */
export const SetActiveLlmProviderRequestSchema: GenMessage<SetActiveLlmProviderRequest, {jsonType: SetActiveLlmProviderRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 3);

/**
 * SetActiveLlmProviderResponse результат активации.
 *
 * @generated from message emh.v1.SetActiveLlmProviderResponse
 */
export type SetActiveLlmProviderResponse = Message<"emh.v1.SetActiveLlmProviderResponse"> & {
  /**
   * success - флаг успешного выполнения операции.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * provider - обновлённая информация о провайдере.
   *
   * @generated from field: emh.v1.LlmProviderInfo provider = 2;
   */
  provider?: LlmProviderInfo | undefined;
};

/**
 * SetActiveLlmProviderResponse результат активации.
 *
 * @generated from message emh.v1.SetActiveLlmProviderResponse
 */
export type SetActiveLlmProviderResponseJson = {
  /**
   * success - флаг успешного выполнения операции.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;

  /**
   * provider - обновлённая информация о провайдере.
   *
   * @generated from field: emh.v1.LlmProviderInfo provider = 2;
   */
  provider?: LlmProviderInfoJson;
};

/**
 * Describes the message emh.v1.SetActiveLlmProviderResponse.
 * Use `create(SetActiveLlmProviderResponseSchema)` to create a new message.
 */
export const SetActiveLlmProviderResponseSchema: GenMessage<SetActiveLlmProviderResponse, {jsonType: SetActiveLlmProviderResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 4);

/**
 * TestLlmProviderRequest запрос на тестирование провайдера.
 *
 * @generated from message emh.v1.TestLlmProviderRequest
 */
export type TestLlmProviderRequest = Message<"emh.v1.TestLlmProviderRequest"> & {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * test_prompt - текст промпта для тестовой генерации.
   *
   * @generated from field: string test_prompt = 2;
   */
  testPrompt: string;
};

/**
 * TestLlmProviderRequest запрос на тестирование провайдера.
 *
 * @generated from message emh.v1.TestLlmProviderRequest
 */
export type TestLlmProviderRequestJson = {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * test_prompt - текст промпта для тестовой генерации.
   *
   * @generated from field: string test_prompt = 2;
   */
  testPrompt?: string;
};

/**
 * Describes the message emh.v1.TestLlmProviderRequest.
 * Use `create(TestLlmProviderRequestSchema)` to create a new message.
 */
export const TestLlmProviderRequestSchema: GenMessage<TestLlmProviderRequest, {jsonType: TestLlmProviderRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 5);

/**
 * TestLlmProviderResponse результат тестирования.
 *
 * @generated from message emh.v1.TestLlmProviderResponse
 */
export type TestLlmProviderResponse = Message<"emh.v1.TestLlmProviderResponse"> & {
  /**
   * success - флаг успешного получения ответа от LLM.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * raw_response - сырой текст ответа от модели.
   *
   * @generated from field: string raw_response = 2;
   */
  rawResponse: string;

  /**
   * processing_time_ms - время выполнения запроса в миллисекундах.
   *
   * @generated from field: int64 processing_time_ms = 3;
   */
  processingTimeMs: bigint;

  /**
   * error_message - текст ошибки, если success = false.
   *
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;
};

/**
 * TestLlmProviderResponse результат тестирования.
 *
 * @generated from message emh.v1.TestLlmProviderResponse
 */
export type TestLlmProviderResponseJson = {
  /**
   * success - флаг успешного получения ответа от LLM.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;

  /**
   * raw_response - сырой текст ответа от модели.
   *
   * @generated from field: string raw_response = 2;
   */
  rawResponse?: string;

  /**
   * processing_time_ms - время выполнения запроса в миллисекундах.
   *
   * @generated from field: int64 processing_time_ms = 3;
   */
  processingTimeMs?: string;

  /**
   * error_message - текст ошибки, если success = false.
   *
   * @generated from field: string error_message = 4;
   */
  errorMessage?: string;
};

/**
 * Describes the message emh.v1.TestLlmProviderResponse.
 * Use `create(TestLlmProviderResponseSchema)` to create a new message.
 */
export const TestLlmProviderResponseSchema: GenMessage<TestLlmProviderResponse, {jsonType: TestLlmProviderResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 6);

/**
 * UpdateLlmProviderRequest запрос на обновление метаданных провайдера.
 *
 * @generated from message emh.v1.UpdateLlmProviderRequest
 */
export type UpdateLlmProviderRequest = Message<"emh.v1.UpdateLlmProviderRequest"> & {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * priority - новый приоритет провайдера.
   *
   * @generated from field: int32 priority = 2;
   */
  priority: number;

  /**
   * notes - новые заметки администратора.
   *
   * @generated from field: string notes = 3;
   */
  notes: string;

  /**
   * field_mask - список обновляемых полей (priority, notes).
   *
   * @generated from field: repeated string field_mask = 4;
   */
  fieldMask: string[];
};

/**
 * UpdateLlmProviderRequest запрос на обновление метаданных провайдера.
 *
 * @generated from message emh.v1.UpdateLlmProviderRequest
 */
export type UpdateLlmProviderRequestJson = {
  /**
   * id - UUID записи провайдера в БД.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * priority - новый приоритет провайдера.
   *
   * @generated from field: int32 priority = 2;
   */
  priority?: number;

  /**
   * notes - новые заметки администратора.
   *
   * @generated from field: string notes = 3;
   */
  notes?: string;

  /**
   * field_mask - список обновляемых полей (priority, notes).
   *
   * @generated from field: repeated string field_mask = 4;
   */
  fieldMask?: string[];
};

/**
 * Describes the message emh.v1.UpdateLlmProviderRequest.
 * Use `create(UpdateLlmProviderRequestSchema)` to create a new message.
 */
export const UpdateLlmProviderRequestSchema: GenMessage<UpdateLlmProviderRequest, {jsonType: UpdateLlmProviderRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 7);

/**
 * UpdateLlmProviderResponse обновлённый провайдер.
 *
 * @generated from message emh.v1.UpdateLlmProviderResponse
 */
export type UpdateLlmProviderResponse = Message<"emh.v1.UpdateLlmProviderResponse"> & {
  /**
   * provider - обновлённая информация о провайдере.
   *
   * @generated from field: emh.v1.LlmProviderInfo provider = 1;
   */
  provider?: LlmProviderInfo | undefined;
};

/**
 * UpdateLlmProviderResponse обновлённый провайдер.
 *
 * @generated from message emh.v1.UpdateLlmProviderResponse
 */
export type UpdateLlmProviderResponseJson = {
  /**
   * provider - обновлённая информация о провайдере.
   *
   * @generated from field: emh.v1.LlmProviderInfo provider = 1;
   */
  provider?: LlmProviderInfoJson;
};

/**
 * Describes the message emh.v1.UpdateLlmProviderResponse.
 * Use `create(UpdateLlmProviderResponseSchema)` to create a new message.
 */
export const UpdateLlmProviderResponseSchema: GenMessage<UpdateLlmProviderResponse, {jsonType: UpdateLlmProviderResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_llm_admin, 8);

/**
 * LlmAdminService админский сервис управления LLM-провайдерами.
 *
 * @generated from service emh.v1.LlmAdminService
 */
export const LlmAdminService: GenService<{
  /**
   * ListLlmProviders возвращает список всех настроенных провайдеров.
   *
   * @generated from rpc emh.v1.LlmAdminService.ListLlmProviders
   */
  listLlmProviders: {
    methodKind: "unary";
    input: typeof ListLlmProvidersRequestSchema;
    output: typeof ListLlmProvidersResponseSchema;
  },
  /**
   * SetActiveLlmProvider активирует указанный провайдер (остальные деактивируются триггером БД).
   *
   * @generated from rpc emh.v1.LlmAdminService.SetActiveLlmProvider
   */
  setActiveLlmProvider: {
    methodKind: "unary";
    input: typeof SetActiveLlmProviderRequestSchema;
    output: typeof SetActiveLlmProviderResponseSchema;
  },
  /**
   * TestLlmProvider отправляет тестовый запрос к провайдеру для проверки доступности.
   *
   * @generated from rpc emh.v1.LlmAdminService.TestLlmProvider
   */
  testLlmProvider: {
    methodKind: "unary";
    input: typeof TestLlmProviderRequestSchema;
    output: typeof TestLlmProviderResponseSchema;
  },
  /**
   * UpdateLlmProvider обновляет приоритет и заметки провайдера.
   *
   * @generated from rpc emh.v1.LlmAdminService.UpdateLlmProvider
   */
  updateLlmProvider: {
    methodKind: "unary";
    input: typeof UpdateLlmProviderRequestSchema;
    output: typeof UpdateLlmProviderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_llm_admin, 0);

