// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/location.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { LocationType, LocationTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { PaginationRequest, PaginationRequestJson, PaginationResponse, PaginationResponseJson } from "./common_pb";
import { file_emh_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/location.proto.
 */
export const file_emh_v1_location: GenFile = /*@__PURE__*/
  fileDesc("ChVlbWgvdjEvbG9jYXRpb24ucHJvdG8SBmVtaC52MSKZAQoITG9jYXRpb24SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIXCg9oaXN0b3JpY2FsX25hbWUYAyABKAkSIgoEdHlwZRgEIAEoDjIULmVtaC52MS5Mb2NhdGlvblR5cGUSEQoJcGFyZW50X2lkGAUgASgJEhAKCGxhdGl0dWRlGAYgASgBEhEKCWxvbmdpdHVkZRgHIAEoASIgChJHZXRMb2NhdGlvblJlcXVlc3QSCgoCaWQYASABKAkiOQoTR2V0TG9jYXRpb25SZXNwb25zZRIiCghsb2NhdGlvbhgBIAEoCzIQLmVtaC52MS5Mb2NhdGlvbiKSAQoUTGlzdExvY2F0aW9uc1JlcXVlc3QSEQoJcGFyZW50X2lkGAEgASgJEhQKDHNlYXJjaF9xdWVyeRgCIAEoCRIiCgR0eXBlGAMgASgOMhQuZW1oLnYxLkxvY2F0aW9uVHlwZRItCgpwYWdpbmF0aW9uGAQgASgLMhkuZW1oLnYxLlBhZ2luYXRpb25SZXF1ZXN0ImwKFUxpc3RMb2NhdGlvbnNSZXNwb25zZRIjCglsb2NhdGlvbnMYASADKAsyEC5lbWgudjEuTG9jYXRpb24SLgoKcGFnaW5hdGlvbhgCIAEoCzIaLmVtaC52MS5QYWdpbmF0aW9uUmVzcG9uc2UypwEKD0xvY2F0aW9uU2VydmljZRJGCgtHZXRMb2NhdGlvbhIaLmVtaC52MS5HZXRMb2NhdGlvblJlcXVlc3QaGy5lbWgudjEuR2V0TG9jYXRpb25SZXNwb25zZRJMCg1MaXN0TG9jYXRpb25zEhwuZW1oLnYxLkxpc3RMb2NhdGlvbnNSZXF1ZXN0Gh0uZW1oLnYxLkxpc3RMb2NhdGlvbnNSZXNwb25zZUI9Wjtjb2RlYmVyZy5vcmcvVGhyMFRUMWUvZW1oL2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2VtaC92MTtlbWh2MWIGcHJvdG8z", [file_emh_v1_enums_emh, file_emh_v1_common]);

/**
 * Location представляет географический объект в справочнике мест.
 *
 * @generated from message emh.v1.Location
 */
export type Location = Message<"emh.v1.Location"> & {
  /**
   * id - уникальный идентификатор локации (UUID).
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - современное название населенного пункта или объекта.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * historical_name - историческое название на период события (опционально).
   *
   * @generated from field: string historical_name = 3;
   */
  historicalName: string;

  /**
   * type - тип географического объекта.
   *
   * @generated from field: emh.v1.LocationType type = 4;
   */
  type: LocationType;

  /**
   * parent_id - ID родительской локации (региона или страны).
   *
   * @generated from field: string parent_id = 5;
   */
  parentId: string;

  /**
   * latitude - широта для отображения на карте.
   *
   * @generated from field: double latitude = 6;
   */
  latitude: number;

  /**
   * longitude - долгота для отображения на карте.
   *
   * @generated from field: double longitude = 7;
   */
  longitude: number;
};

/**
 * Location представляет географический объект в справочнике мест.
 *
 * @generated from message emh.v1.Location
 */
export type LocationJson = {
  /**
   * id - уникальный идентификатор локации (UUID).
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - современное название населенного пункта или объекта.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * historical_name - историческое название на период события (опционально).
   *
   * @generated from field: string historical_name = 3;
   */
  historicalName?: string;

  /**
   * type - тип географического объекта.
   *
   * @generated from field: emh.v1.LocationType type = 4;
   */
  type?: LocationTypeJson;

  /**
   * parent_id - ID родительской локации (региона или страны).
   *
   * @generated from field: string parent_id = 5;
   */
  parentId?: string;

  /**
   * latitude - широта для отображения на карте.
   *
   * @generated from field: double latitude = 6;
   */
  latitude?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * longitude - долгота для отображения на карте.
   *
   * @generated from field: double longitude = 7;
   */
  longitude?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message emh.v1.Location.
 * Use `create(LocationSchema)` to create a new message.
 */
export const LocationSchema: GenMessage<Location, {jsonType: LocationJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location, 0);

/**
 * GetLocationRequest запрос на получение локации по ID.
 *
 * @generated from message emh.v1.GetLocationRequest
 */
export type GetLocationRequest = Message<"emh.v1.GetLocationRequest"> & {
  /**
   * id - UUID локации.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * GetLocationRequest запрос на получение локации по ID.
 *
 * @generated from message emh.v1.GetLocationRequest
 */
export type GetLocationRequestJson = {
  /**
   * id - UUID локации.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.GetLocationRequest.
 * Use `create(GetLocationRequestSchema)` to create a new message.
 */
export const GetLocationRequestSchema: GenMessage<GetLocationRequest, {jsonType: GetLocationRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location, 1);

/**
 * GetLocationResponse ответ с данными локации.
 *
 * @generated from message emh.v1.GetLocationResponse
 */
export type GetLocationResponse = Message<"emh.v1.GetLocationResponse"> & {
  /**
   * location - объект локации.
   *
   * @generated from field: emh.v1.Location location = 1;
   */
  location?: Location | undefined;
};

/**
 * GetLocationResponse ответ с данными локации.
 *
 * @generated from message emh.v1.GetLocationResponse
 */
export type GetLocationResponseJson = {
  /**
   * location - объект локации.
   *
   * @generated from field: emh.v1.Location location = 1;
   */
  location?: LocationJson;
};

/**
 * Describes the message emh.v1.GetLocationResponse.
 * Use `create(GetLocationResponseSchema)` to create a new message.
 */
export const GetLocationResponseSchema: GenMessage<GetLocationResponse, {jsonType: GetLocationResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location, 2);

/**
 * ListLocationsRequest параметры выборки локаций.
 *
 * @generated from message emh.v1.ListLocationsRequest
 */
export type ListLocationsRequest = Message<"emh.v1.ListLocationsRequest"> & {
  /**
   * parent_id - фильтр по родительской локации (например, города области).
   *
   * @generated from field: string parent_id = 1;
   */
  parentId: string;

  /**
   * search_query - текстовый поиск по названию.
   *
   * @generated from field: string search_query = 2;
   */
  searchQuery: string;

  /**
   * type - фильтр по типу локации.
   *
   * @generated from field: emh.v1.LocationType type = 3;
   */
  type: LocationType;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 4;
   */
  pagination?: PaginationRequest | undefined;
};

/**
 * ListLocationsRequest параметры выборки локаций.
 *
 * @generated from message emh.v1.ListLocationsRequest
 */
export type ListLocationsRequestJson = {
  /**
   * parent_id - фильтр по родительской локации (например, города области).
   *
   * @generated from field: string parent_id = 1;
   */
  parentId?: string;

  /**
   * search_query - текстовый поиск по названию.
   *
   * @generated from field: string search_query = 2;
   */
  searchQuery?: string;

  /**
   * type - фильтр по типу локации.
   *
   * @generated from field: emh.v1.LocationType type = 3;
   */
  type?: LocationTypeJson;

  /**
   * pagination - параметры курсорной пагинации.
   *
   * @generated from field: emh.v1.PaginationRequest pagination = 4;
   */
  pagination?: PaginationRequestJson;
};

/**
 * Describes the message emh.v1.ListLocationsRequest.
 * Use `create(ListLocationsRequestSchema)` to create a new message.
 */
export const ListLocationsRequestSchema: GenMessage<ListLocationsRequest, {jsonType: ListLocationsRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location, 3);

/**
 * ListLocationsResponse список найденных локаций.
 *
 * @generated from message emh.v1.ListLocationsResponse
 */
export type ListLocationsResponse = Message<"emh.v1.ListLocationsResponse"> & {
  /**
   * locations - массив объектов локаций.
   *
   * @generated from field: repeated emh.v1.Location locations = 1;
   */
  locations: Location[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse | undefined;
};

/**
 * ListLocationsResponse список найденных локаций.
 *
 * @generated from message emh.v1.ListLocationsResponse
 */
export type ListLocationsResponseJson = {
  /**
   * locations - массив объектов локаций.
   *
   * @generated from field: repeated emh.v1.Location locations = 1;
   */
  locations?: LocationJson[];

  /**
   * pagination - метаданные для перехода к следующей странице.
   *
   * @generated from field: emh.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponseJson;
};

/**
 * Describes the message emh.v1.ListLocationsResponse.
 * Use `create(ListLocationsResponseSchema)` to create a new message.
 */
export const ListLocationsResponseSchema: GenMessage<ListLocationsResponse, {jsonType: ListLocationsResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location, 4);

/**
 * LocationService публичный сервис для работы со справочником мест.
 *
 * @generated from service emh.v1.LocationService
 */
export const LocationService: GenService<{
  /**
   * GetLocation возвращает локацию по ID.
   *
   * @generated from rpc emh.v1.LocationService.GetLocation
   */
  getLocation: {
    methodKind: "unary";
    input: typeof GetLocationRequestSchema;
    output: typeof GetLocationResponseSchema;
  },
  /**
   * ListLocations возвращает отфильтрованный список локаций.
   *
   * @generated from rpc emh.v1.LocationService.ListLocations
   */
  listLocations: {
    methodKind: "unary";
    input: typeof ListLocationsRequestSchema;
    output: typeof ListLocationsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_location, 0);

