// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/location_admin.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { LocationType, LocationTypeJson } from "./enums_emh_pb";
import { file_emh_v1_enums_emh } from "./enums_emh_pb";
import type { Location, LocationJson } from "./location_pb";
import { file_emh_v1_location } from "./location_pb";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/location_admin.proto.
 */
export const file_emh_v1_location_admin: GenFile = /*@__PURE__*/
  fileDesc("ChtlbWgvdjEvbG9jYXRpb25fYWRtaW4ucHJvdG8SBmVtaC52MSLsAQoVQ3JlYXRlTG9jYXRpb25SZXF1ZXN0EhUKBG5hbWUYASABKAlCB7pIBHICEAESFwoPaGlzdG9yaWNhbF9uYW1lGAIgASgJEiwKBHR5cGUYAyABKA4yFC5lbWgudjEuTG9jYXRpb25UeXBlQgi6SAWCAQIgABIeCglwYXJlbnRfaWQYBCABKAlCC7pICHIDsAEB2AEBEikKCGxhdGl0dWRlGAUgASgBQhe6SBQSEikAAAAAAIBWwBkAAAAAAIBWQBIqCglsb25naXR1ZGUYBiABKAFCF7pIFBISGQAAAAAAgGZAKQAAAAAAgGbAIiQKFkNyZWF0ZUxvY2F0aW9uUmVzcG9uc2USCgoCaWQYASABKAkiogIKFVVwZGF0ZUxvY2F0aW9uUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOwAQESGAoEbmFtZRgCIAEoCUIKukgHcgIQAdgBARIXCg9oaXN0b3JpY2FsX25hbWUYAyABKAkSLwoEdHlwZRgEIAEoDjIULmVtaC52MS5Mb2NhdGlvblR5cGVCC7pICIIBAiAA2AEBEh4KCXBhcmVudF9pZBgFIAEoCUILukgIcgOwAQHYAQESLAoIbGF0aXR1ZGUYBiABKAFCGrpIFxISKQAAAAAAgFbAGQAAAAAAgFZA2AEBEi0KCWxvbmdpdHVkZRgHIAEoAUIaukgXEhIpAAAAAACAZsAZAAAAAACAZkDYAQESEgoKZmllbGRfbWFzaxgIIAMoCSI8ChZVcGRhdGVMb2NhdGlvblJlc3BvbnNlEiIKCGxvY2F0aW9uGAEgASgLMhAuZW1oLnYxLkxvY2F0aW9uIi0KFURlbGV0ZUxvY2F0aW9uUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOwAQEiKQoWRGVsZXRlTG9jYXRpb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIlwKGFJlcGFyZW50TG9jYXRpb25zUmVxdWVzdBIfCg1vbGRfcGFyZW50X2lkGAEgASgJQgi6SAVyA7ABARIfCg1uZXdfcGFyZW50X2lkGAIgASgJQgi6SAVyA7ABASIzChlSZXBhcmVudExvY2F0aW9uc1Jlc3BvbnNlEhYKDmFmZmVjdGVkX2NvdW50GAEgASgFMuMCChRMb2NhdGlvbkFkbWluU2VydmljZRJPCg5DcmVhdGVMb2NhdGlvbhIdLmVtaC52MS5DcmVhdGVMb2NhdGlvblJlcXVlc3QaHi5lbWgudjEuQ3JlYXRlTG9jYXRpb25SZXNwb25zZRJPCg5VcGRhdGVMb2NhdGlvbhIdLmVtaC52MS5VcGRhdGVMb2NhdGlvblJlcXVlc3QaHi5lbWgudjEuVXBkYXRlTG9jYXRpb25SZXNwb25zZRJPCg5EZWxldGVMb2NhdGlvbhIdLmVtaC52MS5EZWxldGVMb2NhdGlvblJlcXVlc3QaHi5lbWgudjEuRGVsZXRlTG9jYXRpb25SZXNwb25zZRJYChFSZXBhcmVudExvY2F0aW9ucxIgLmVtaC52MS5SZXBhcmVudExvY2F0aW9uc1JlcXVlc3QaIS5lbWgudjEuUmVwYXJlbnRMb2NhdGlvbnNSZXNwb25zZUI9Wjtjb2RlYmVyZy5vcmcvVGhyMFRUMWUvZW1oL2JhY2tlbmQvaW50ZXJuYWwvZ2VuL2VtaC92MTtlbWh2MWIGcHJvdG8z", [file_emh_v1_enums_emh, file_emh_v1_location, file_buf_validate_validate]);

/**
 * CreateLocationRequest данные для создания новой локации.
 *
 * @generated from message emh.v1.CreateLocationRequest
 */
export type CreateLocationRequest = Message<"emh.v1.CreateLocationRequest"> & {
  /**
   * name - современное название (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * historical_name - историческое название (опционально).
   *
   * @generated from field: string historical_name = 2;
   */
  historicalName: string;

  /**
   * type - тип географического объекта.
   *
   * @generated from field: emh.v1.LocationType type = 3;
   */
  type: LocationType;

  /**
   * parent_id - ID родительской локации.
   *
   * @generated from field: string parent_id = 4;
   */
  parentId: string;

  /**
   * latitude - широта центра объекта (-90..90).
   *
   * @generated from field: double latitude = 5;
   */
  latitude: number;

  /**
   * longitude - долгота центра объекта (-180..180).
   *
   * @generated from field: double longitude = 6;
   */
  longitude: number;
};

/**
 * CreateLocationRequest данные для создания новой локации.
 *
 * @generated from message emh.v1.CreateLocationRequest
 */
export type CreateLocationRequestJson = {
  /**
   * name - современное название (обязательно).
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * historical_name - историческое название (опционально).
   *
   * @generated from field: string historical_name = 2;
   */
  historicalName?: string;

  /**
   * type - тип географического объекта.
   *
   * @generated from field: emh.v1.LocationType type = 3;
   */
  type?: LocationTypeJson;

  /**
   * parent_id - ID родительской локации.
   *
   * @generated from field: string parent_id = 4;
   */
  parentId?: string;

  /**
   * latitude - широта центра объекта (-90..90).
   *
   * @generated from field: double latitude = 5;
   */
  latitude?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * longitude - долгота центра объекта (-180..180).
   *
   * @generated from field: double longitude = 6;
   */
  longitude?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message emh.v1.CreateLocationRequest.
 * Use `create(CreateLocationRequestSchema)` to create a new message.
 */
export const CreateLocationRequestSchema: GenMessage<CreateLocationRequest, {jsonType: CreateLocationRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 0);

/**
 * CreateLocationResponse результат создания локации.
 *
 * @generated from message emh.v1.CreateLocationResponse
 */
export type CreateLocationResponse = Message<"emh.v1.CreateLocationResponse"> & {
  /**
   * id - UUID созданной локации.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * CreateLocationResponse результат создания локации.
 *
 * @generated from message emh.v1.CreateLocationResponse
 */
export type CreateLocationResponseJson = {
  /**
   * id - UUID созданной локации.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.CreateLocationResponse.
 * Use `create(CreateLocationResponseSchema)` to create a new message.
 */
export const CreateLocationResponseSchema: GenMessage<CreateLocationResponse, {jsonType: CreateLocationResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 1);

/**
 * UpdateLocationRequest данные для частичного обновления локации.
 *
 * @generated from message emh.v1.UpdateLocationRequest
 */
export type UpdateLocationRequest = Message<"emh.v1.UpdateLocationRequest"> & {
  /**
   * id - UUID обновляемой локации.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name - новое современное название.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * historical_name - новое историческое название.
   *
   * @generated from field: string historical_name = 3;
   */
  historicalName: string;

  /**
   * type - новый тип локации.
   *
   * @generated from field: emh.v1.LocationType type = 4;
   */
  type: LocationType;

  /**
   * parent_id - новый ID родительской локации.
   *
   * @generated from field: string parent_id = 5;
   */
  parentId: string;

  /**
   * latitude - новая широта.
   *
   * @generated from field: double latitude = 6;
   */
  latitude: number;

  /**
   * longitude - новая долгота.
   *
   * @generated from field: double longitude = 7;
   */
  longitude: number;

  /**
   * field_mask - список полей для обновления.
   *
   * @generated from field: repeated string field_mask = 8;
   */
  fieldMask: string[];
};

/**
 * UpdateLocationRequest данные для частичного обновления локации.
 *
 * @generated from message emh.v1.UpdateLocationRequest
 */
export type UpdateLocationRequestJson = {
  /**
   * id - UUID обновляемой локации.
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * name - новое современное название.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * historical_name - новое историческое название.
   *
   * @generated from field: string historical_name = 3;
   */
  historicalName?: string;

  /**
   * type - новый тип локации.
   *
   * @generated from field: emh.v1.LocationType type = 4;
   */
  type?: LocationTypeJson;

  /**
   * parent_id - новый ID родительской локации.
   *
   * @generated from field: string parent_id = 5;
   */
  parentId?: string;

  /**
   * latitude - новая широта.
   *
   * @generated from field: double latitude = 6;
   */
  latitude?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * longitude - новая долгота.
   *
   * @generated from field: double longitude = 7;
   */
  longitude?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * field_mask - список полей для обновления.
   *
   * @generated from field: repeated string field_mask = 8;
   */
  fieldMask?: string[];
};

/**
 * Describes the message emh.v1.UpdateLocationRequest.
 * Use `create(UpdateLocationRequestSchema)` to create a new message.
 */
export const UpdateLocationRequestSchema: GenMessage<UpdateLocationRequest, {jsonType: UpdateLocationRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 2);

/**
 * UpdateLocationResponse обновленный объект локации.
 *
 * @generated from message emh.v1.UpdateLocationResponse
 */
export type UpdateLocationResponse = Message<"emh.v1.UpdateLocationResponse"> & {
  /**
   * location - актуальное состояние локации.
   *
   * @generated from field: emh.v1.Location location = 1;
   */
  location?: Location | undefined;
};

/**
 * UpdateLocationResponse обновленный объект локации.
 *
 * @generated from message emh.v1.UpdateLocationResponse
 */
export type UpdateLocationResponseJson = {
  /**
   * location - актуальное состояние локации.
   *
   * @generated from field: emh.v1.Location location = 1;
   */
  location?: LocationJson;
};

/**
 * Describes the message emh.v1.UpdateLocationResponse.
 * Use `create(UpdateLocationResponseSchema)` to create a new message.
 */
export const UpdateLocationResponseSchema: GenMessage<UpdateLocationResponse, {jsonType: UpdateLocationResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 3);

/**
 * DeleteLocationRequest запрос на удаление локации.
 *
 * @generated from message emh.v1.DeleteLocationRequest
 */
export type DeleteLocationRequest = Message<"emh.v1.DeleteLocationRequest"> & {
  /**
   * id - UUID удаляемой локации.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * DeleteLocationRequest запрос на удаление локации.
 *
 * @generated from message emh.v1.DeleteLocationRequest
 */
export type DeleteLocationRequestJson = {
  /**
   * id - UUID удаляемой локации.
   *
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message emh.v1.DeleteLocationRequest.
 * Use `create(DeleteLocationRequestSchema)` to create a new message.
 */
export const DeleteLocationRequestSchema: GenMessage<DeleteLocationRequest, {jsonType: DeleteLocationRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 4);

/**
 * DeleteLocationResponse подтверждение удаления.
 *
 * @generated from message emh.v1.DeleteLocationResponse
 */
export type DeleteLocationResponse = Message<"emh.v1.DeleteLocationResponse"> & {
  /**
   * success - true если удаление успешно.
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * DeleteLocationResponse подтверждение удаления.
 *
 * @generated from message emh.v1.DeleteLocationResponse
 */
export type DeleteLocationResponseJson = {
  /**
   * success - true если удаление успешно.
   *
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message emh.v1.DeleteLocationResponse.
 * Use `create(DeleteLocationResponseSchema)` to create a new message.
 */
export const DeleteLocationResponseSchema: GenMessage<DeleteLocationResponse, {jsonType: DeleteLocationResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 5);

/**
 * ReparentLocationsRequest запрос на массовую перепривязку дочерних локаций.
 *
 * @generated from message emh.v1.ReparentLocationsRequest
 */
export type ReparentLocationsRequest = Message<"emh.v1.ReparentLocationsRequest"> & {
  /**
   * old_parent_id - ID старого родителя.
   *
   * @generated from field: string old_parent_id = 1;
   */
  oldParentId: string;

  /**
   * new_parent_id - ID нового родителя.
   *
   * @generated from field: string new_parent_id = 2;
   */
  newParentId: string;
};

/**
 * ReparentLocationsRequest запрос на массовую перепривязку дочерних локаций.
 *
 * @generated from message emh.v1.ReparentLocationsRequest
 */
export type ReparentLocationsRequestJson = {
  /**
   * old_parent_id - ID старого родителя.
   *
   * @generated from field: string old_parent_id = 1;
   */
  oldParentId?: string;

  /**
   * new_parent_id - ID нового родителя.
   *
   * @generated from field: string new_parent_id = 2;
   */
  newParentId?: string;
};

/**
 * Describes the message emh.v1.ReparentLocationsRequest.
 * Use `create(ReparentLocationsRequestSchema)` to create a new message.
 */
export const ReparentLocationsRequestSchema: GenMessage<ReparentLocationsRequest, {jsonType: ReparentLocationsRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 6);

/**
 * ReparentLocationsResponse результат операции перепривязки.
 *
 * @generated from message emh.v1.ReparentLocationsResponse
 */
export type ReparentLocationsResponse = Message<"emh.v1.ReparentLocationsResponse"> & {
  /**
   * affected_count - количество успешно перенесенных локаций.
   *
   * @generated from field: int32 affected_count = 1;
   */
  affectedCount: number;
};

/**
 * ReparentLocationsResponse результат операции перепривязки.
 *
 * @generated from message emh.v1.ReparentLocationsResponse
 */
export type ReparentLocationsResponseJson = {
  /**
   * affected_count - количество успешно перенесенных локаций.
   *
   * @generated from field: int32 affected_count = 1;
   */
  affectedCount?: number;
};

/**
 * Describes the message emh.v1.ReparentLocationsResponse.
 * Use `create(ReparentLocationsResponseSchema)` to create a new message.
 */
export const ReparentLocationsResponseSchema: GenMessage<ReparentLocationsResponse, {jsonType: ReparentLocationsResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_location_admin, 7);

/**
 * LocationAdminService защищенный сервис для управления справочником мест.
 *
 * @generated from service emh.v1.LocationAdminService
 */
export const LocationAdminService: GenService<{
  /**
   * CreateLocation создает новую запись в справочнике мест.
   *
   * @generated from rpc emh.v1.LocationAdminService.CreateLocation
   */
  createLocation: {
    methodKind: "unary";
    input: typeof CreateLocationRequestSchema;
    output: typeof CreateLocationResponseSchema;
  },
  /**
   * UpdateLocation частично обновляет существующую локацию.
   *
   * @generated from rpc emh.v1.LocationAdminService.UpdateLocation
   */
  updateLocation: {
    methodKind: "unary";
    input: typeof UpdateLocationRequestSchema;
    output: typeof UpdateLocationResponseSchema;
  },
  /**
   * DeleteLocation удаляет локацию (требует предварительной репривязки детей).
   *
   * @generated from rpc emh.v1.LocationAdminService.DeleteLocation
   */
  deleteLocation: {
    methodKind: "unary";
    input: typeof DeleteLocationRequestSchema;
    output: typeof DeleteLocationResponseSchema;
  },
  /**
   * ReparentLocations массово переносит дочерние локации к новому родителю.
   *
   * @generated from rpc emh.v1.LocationAdminService.ReparentLocations
   */
  reparentLocations: {
    methodKind: "unary";
    input: typeof ReparentLocationsRequestSchema;
    output: typeof ReparentLocationsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_location_admin, 0);

