// Сервис для загрузки файлов.

// @generated by protoc-gen-es v2.13.0 with parameter "json_types=true,target=ts"
// @generated from file emh/v1/media.proto (package emh.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file emh/v1/media.proto.
 */
export const file_emh_v1_media: GenFile = /*@__PURE__*/
  fileDesc("ChJlbWgvdjEvbWVkaWEucHJvdG8SBmVtaC52MSJ7ChNHZXRVcGxvYWRVcmxSZXF1ZXN0EioKBHR5cGUYASABKA4yEi5lbWgudjEuVXBsb2FkVHlwZUIIukgFggECIAASGQoIZmlsZW5hbWUYAiABKAlCB7pIBHICEAESHQoMY29udGVudF90eXBlGAMgASgJQge6SARyAhABIlIKFEdldFVwbG9hZFVybFJlc3BvbnNlEhIKCnVwbG9hZF91cmwYASABKAkSEgoKcHVibGljX3VybBgCIAEoCRISCgpleHBpcmVzX2F0GAMgASgJIngKGUJhdGNoR2V0VXBsb2FkVXJsc1JlcXVlc3QSLwoFZmlsZXMYASADKAsyFC5lbWgudjEuRmlsZVRvVXBsb2FkQgq6SAeSAQQIARAyEioKBHR5cGUYAiABKA4yEi5lbWgudjEuVXBsb2FkVHlwZUIIukgFggECIAAiUAoaQmF0Y2hHZXRVcGxvYWRVcmxzUmVzcG9uc2USIwoEdXJscxgBIAMoCzIVLmVtaC52MS5VcGxvYWRVcmxJbmZvEg0KBWNvdW50GAIgASgFIkgKDEZpbGVUb1VwbG9hZBIZCghmaWxlbmFtZRgBIAEoCUIHukgEcgIQARIdCgxjb250ZW50X3R5cGUYAiABKAlCB7pIBHICEAEiXQoNVXBsb2FkVXJsSW5mbxIQCghmaWxlbmFtZRgBIAEoCRISCgp1cGxvYWRfdXJsGAIgASgJEhIKCnB1YmxpY191cmwYAyABKAkSEgoKZXhwaXJlc19hdBgEIAEoCSqJAQoKVXBsb2FkVHlwZRIbChdVUExPQURfVFlQRV9VTlNQRUNJRklFRBAAEhoKFlVQTE9BRF9UWVBFX0hFUk9fUEhPVE8QARIbChdVUExPQURfVFlQRV9BV0FSRF9JTUFHRRACEiUKIVVQTE9BRF9UWVBFX1NVQk1JU1NJT05fQVRUQUNITUVOVBADMrYBCgxNZWRpYVNlcnZpY2USSQoMR2V0VXBsb2FkVXJsEhsuZW1oLnYxLkdldFVwbG9hZFVybFJlcXVlc3QaHC5lbWgudjEuR2V0VXBsb2FkVXJsUmVzcG9uc2USWwoSQmF0Y2hHZXRVcGxvYWRVcmxzEiEuZW1oLnYxLkJhdGNoR2V0VXBsb2FkVXJsc1JlcXVlc3QaIi5lbWgudjEuQmF0Y2hHZXRVcGxvYWRVcmxzUmVzcG9uc2VCPVo7Y29kZWJlcmcub3JnL1RocjBUVDFlL2VtaC9iYWNrZW5kL2ludGVybmFsL2dlbi9lbWgvdjE7ZW1odjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * GetUploadUrlRequest запрос на получение presigned URL для загрузки.
 *
 * @generated from message emh.v1.GetUploadUrlRequest
 */
export type GetUploadUrlRequest = Message<"emh.v1.GetUploadUrlRequest"> & {
  /**
   * type - тип загружаемого контента.
   *
   * @generated from field: emh.v1.UploadType type = 1;
   */
  type: UploadType;

  /**
   * filename - оригинальное имя файла.
   *
   * @generated from field: string filename = 2;
   */
  filename: string;

  /**
   * content_type - MIME-тип файла.
   *
   * @generated from field: string content_type = 3;
   */
  contentType: string;
};

/**
 * GetUploadUrlRequest запрос на получение presigned URL для загрузки.
 *
 * @generated from message emh.v1.GetUploadUrlRequest
 */
export type GetUploadUrlRequestJson = {
  /**
   * type - тип загружаемого контента.
   *
   * @generated from field: emh.v1.UploadType type = 1;
   */
  type?: UploadTypeJson;

  /**
   * filename - оригинальное имя файла.
   *
   * @generated from field: string filename = 2;
   */
  filename?: string;

  /**
   * content_type - MIME-тип файла.
   *
   * @generated from field: string content_type = 3;
   */
  contentType?: string;
};

/**
 * Describes the message emh.v1.GetUploadUrlRequest.
 * Use `create(GetUploadUrlRequestSchema)` to create a new message.
 */
export const GetUploadUrlRequestSchema: GenMessage<GetUploadUrlRequest, {jsonType: GetUploadUrlRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 0);

/**
 * GetUploadUrlResponse содержит URL для прямой загрузки и будущий публичный путь.
 *
 * @generated from message emh.v1.GetUploadUrlResponse
 */
export type GetUploadUrlResponse = Message<"emh.v1.GetUploadUrlResponse"> & {
  /**
   * upload_url - presigned PUT URL для загрузки файла в S3/MinIO.
   *
   * @generated from field: string upload_url = 1;
   */
  uploadUrl: string;

  /**
   * public_url - финальный публичный URL файла после успешной загрузки.
   *
   * @generated from field: string public_url = 2;
   */
  publicUrl: string;

  /**
   * expires_at - время истечения действия presigned URL (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt: string;
};

/**
 * GetUploadUrlResponse содержит URL для прямой загрузки и будущий публичный путь.
 *
 * @generated from message emh.v1.GetUploadUrlResponse
 */
export type GetUploadUrlResponseJson = {
  /**
   * upload_url - presigned PUT URL для загрузки файла в S3/MinIO.
   *
   * @generated from field: string upload_url = 1;
   */
  uploadUrl?: string;

  /**
   * public_url - финальный публичный URL файла после успешной загрузки.
   *
   * @generated from field: string public_url = 2;
   */
  publicUrl?: string;

  /**
   * expires_at - время истечения действия presigned URL (RFC3339).
   *
   * @generated from field: string expires_at = 3;
   */
  expiresAt?: string;
};

/**
 * Describes the message emh.v1.GetUploadUrlResponse.
 * Use `create(GetUploadUrlResponseSchema)` to create a new message.
 */
export const GetUploadUrlResponseSchema: GenMessage<GetUploadUrlResponse, {jsonType: GetUploadUrlResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 1);

/**
 * BatchGetUploadUrlsRequest Batch-запрос для пакетной генерации presigned URL
 *
 * @generated from message emh.v1.BatchGetUploadUrlsRequest
 */
export type BatchGetUploadUrlsRequest = Message<"emh.v1.BatchGetUploadUrlsRequest"> & {
  /**
   * files - список файлов для загрузки (не более 50 за один запрос).
   *
   * @generated from field: repeated emh.v1.FileToUpload files = 1;
   */
  files: FileToUpload[];

  /**
   * type - тип загружаемого контента (одинаковый для всех файлов в пакете).
   *
   * @generated from field: emh.v1.UploadType type = 2;
   */
  type: UploadType;
};

/**
 * BatchGetUploadUrlsRequest Batch-запрос для пакетной генерации presigned URL
 *
 * @generated from message emh.v1.BatchGetUploadUrlsRequest
 */
export type BatchGetUploadUrlsRequestJson = {
  /**
   * files - список файлов для загрузки (не более 50 за один запрос).
   *
   * @generated from field: repeated emh.v1.FileToUpload files = 1;
   */
  files?: FileToUploadJson[];

  /**
   * type - тип загружаемого контента (одинаковый для всех файлов в пакете).
   *
   * @generated from field: emh.v1.UploadType type = 2;
   */
  type?: UploadTypeJson;
};

/**
 * Describes the message emh.v1.BatchGetUploadUrlsRequest.
 * Use `create(BatchGetUploadUrlsRequestSchema)` to create a new message.
 */
export const BatchGetUploadUrlsRequestSchema: GenMessage<BatchGetUploadUrlsRequest, {jsonType: BatchGetUploadUrlsRequestJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 2);

/**
 * BatchGetUploadUrlsResponse Batch-ответ с массивом presigned URL
 *
 * @generated from message emh.v1.BatchGetUploadUrlsResponse
 */
export type BatchGetUploadUrlsResponse = Message<"emh.v1.BatchGetUploadUrlsResponse"> & {
  /**
   * urls - массив presigned URL для каждого файла.
   *
   * @generated from field: repeated emh.v1.UploadUrlInfo urls = 1;
   */
  urls: UploadUrlInfo[];

  /**
   * count - количество сгенерированных URL.
   *
   * @generated from field: int32 count = 2;
   */
  count: number;
};

/**
 * BatchGetUploadUrlsResponse Batch-ответ с массивом presigned URL
 *
 * @generated from message emh.v1.BatchGetUploadUrlsResponse
 */
export type BatchGetUploadUrlsResponseJson = {
  /**
   * urls - массив presigned URL для каждого файла.
   *
   * @generated from field: repeated emh.v1.UploadUrlInfo urls = 1;
   */
  urls?: UploadUrlInfoJson[];

  /**
   * count - количество сгенерированных URL.
   *
   * @generated from field: int32 count = 2;
   */
  count?: number;
};

/**
 * Describes the message emh.v1.BatchGetUploadUrlsResponse.
 * Use `create(BatchGetUploadUrlsResponseSchema)` to create a new message.
 */
export const BatchGetUploadUrlsResponseSchema: GenMessage<BatchGetUploadUrlsResponse, {jsonType: BatchGetUploadUrlsResponseJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 3);

/**
 * FileToUpload Описание одного файла для batch-загрузки
 *
 * @generated from message emh.v1.FileToUpload
 */
export type FileToUpload = Message<"emh.v1.FileToUpload"> & {
  /**
   * filename - оригинальное имя файла.
   *
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * content_type - MIME-тип файла.
   *
   * @generated from field: string content_type = 2;
   */
  contentType: string;
};

/**
 * FileToUpload Описание одного файла для batch-загрузки
 *
 * @generated from message emh.v1.FileToUpload
 */
export type FileToUploadJson = {
  /**
   * filename - оригинальное имя файла.
   *
   * @generated from field: string filename = 1;
   */
  filename?: string;

  /**
   * content_type - MIME-тип файла.
   *
   * @generated from field: string content_type = 2;
   */
  contentType?: string;
};

/**
 * Describes the message emh.v1.FileToUpload.
 * Use `create(FileToUploadSchema)` to create a new message.
 */
export const FileToUploadSchema: GenMessage<FileToUpload, {jsonType: FileToUploadJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 4);

/**
 * UploadUrlInfo Элемент batch-ответа
 *
 * @generated from message emh.v1.UploadUrlInfo
 */
export type UploadUrlInfo = Message<"emh.v1.UploadUrlInfo"> & {
  /**
   * filename - имя файла (для маппинга на фронтенде).
   *
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * upload_url - presigned PUT URL для загрузки файла в S3/MinIO.
   *
   * @generated from field: string upload_url = 2;
   */
  uploadUrl: string;

  /**
   * public_url - финальный публичный URL файла после успешной загрузки.
   *
   * @generated from field: string public_url = 3;
   */
  publicUrl: string;

  /**
   * expires_at - время истечения действия presigned URL (RFC3339).
   *
   * @generated from field: string expires_at = 4;
   */
  expiresAt: string;
};

/**
 * UploadUrlInfo Элемент batch-ответа
 *
 * @generated from message emh.v1.UploadUrlInfo
 */
export type UploadUrlInfoJson = {
  /**
   * filename - имя файла (для маппинга на фронтенде).
   *
   * @generated from field: string filename = 1;
   */
  filename?: string;

  /**
   * upload_url - presigned PUT URL для загрузки файла в S3/MinIO.
   *
   * @generated from field: string upload_url = 2;
   */
  uploadUrl?: string;

  /**
   * public_url - финальный публичный URL файла после успешной загрузки.
   *
   * @generated from field: string public_url = 3;
   */
  publicUrl?: string;

  /**
   * expires_at - время истечения действия presigned URL (RFC3339).
   *
   * @generated from field: string expires_at = 4;
   */
  expiresAt?: string;
};

/**
 * Describes the message emh.v1.UploadUrlInfo.
 * Use `create(UploadUrlInfoSchema)` to create a new message.
 */
export const UploadUrlInfoSchema: GenMessage<UploadUrlInfo, {jsonType: UploadUrlInfoJson}> = /*@__PURE__*/
  messageDesc(file_emh_v1_media, 5);

/**
 * UploadType определяет назначение загружаемого файла.
 *
 * @generated from enum emh.v1.UploadType
 */
export enum UploadType {
  /**
   * UPLOAD_TYPE_UNSPECIFIED - тип не задан.
   *
   * @generated from enum value: UPLOAD_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * UPLOAD_TYPE_HERO_PHOTO - фотография героя.
   *
   * @generated from enum value: UPLOAD_TYPE_HERO_PHOTO = 1;
   */
  HERO_PHOTO = 1,

  /**
   * UPLOAD_TYPE_AWARD_IMAGE - изображение награды.
   *
   * @generated from enum value: UPLOAD_TYPE_AWARD_IMAGE = 2;
   */
  AWARD_IMAGE = 2,

  /**
   * UPLOAD_TYPE_SUBMISSION_ATTACHMENT - документ к заявке.
   *
   * @generated from enum value: UPLOAD_TYPE_SUBMISSION_ATTACHMENT = 3;
   */
  SUBMISSION_ATTACHMENT = 3,
}

/**
 * UploadType определяет назначение загружаемого файла.
 *
 * @generated from enum emh.v1.UploadType
 */
export type UploadTypeJson = "UPLOAD_TYPE_UNSPECIFIED" | "UPLOAD_TYPE_HERO_PHOTO" | "UPLOAD_TYPE_AWARD_IMAGE" | "UPLOAD_TYPE_SUBMISSION_ATTACHMENT";

/**
 * Describes the enum emh.v1.UploadType.
 */
export const UploadTypeSchema: GenEnum<UploadType, UploadTypeJson> = /*@__PURE__*/
  enumDesc(file_emh_v1_media, 0);

/**
 * MediaService сервис для работы с медиа-контентом.
 *
 * @generated from service emh.v1.MediaService
 */
export const MediaService: GenService<{
  /**
   * GetUploadUrl генерирует presigned URL для безопасной прямой загрузки в хранилище.
   *
   * @generated from rpc emh.v1.MediaService.GetUploadUrl
   */
  getUploadUrl: {
    methodKind: "unary";
    input: typeof GetUploadUrlRequestSchema;
    output: typeof GetUploadUrlResponseSchema;
  },
  /**
   * BatchGetUploadUrls генерирует несколько presigned URL за один запрос.
   *
   * @generated from rpc emh.v1.MediaService.BatchGetUploadUrls
   */
  batchGetUploadUrls: {
    methodKind: "unary";
    input: typeof BatchGetUploadUrlsRequestSchema;
    output: typeof BatchGetUploadUrlsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_emh_v1_media, 0);

