ssl = on
ssl_cert_file = '/var/lib/postgresql/certs/server.pem'
ssl_key_file = '/var/lib/postgresql/certs/server-key.pem'
ssl_ca_file = '/var/lib/postgresql/certs/ca.pem'
ssl_ciphers = 'HIGH:!aNULL:!MD5'